#define EMOJI_HASH @{ \
@":grinning:" : @"\\uD83D\\uDE00", \
@":smiley:" : @"\\uD83D\\uDE03", \
@":smile:" : @"\\uD83D\\uDE04", \
@":grin:" : @"\\uD83D\\uDE01", \
@":laughing:" : @"\\uD83D\\uDE06", \
@":satisfied:" : @"\\uD83D\\uDE06", \
@":face_holding_back_tears:" : @"\\uD83E\\uDD79", \
@":sweat_smile:" : @"\\uD83D\\uDE05", \
@":joy:" : @"\\uD83D\\uDE02", \
@":rofl:" : @"\\uD83E\\uDD23", \
@":rolling_on_the_floor_laughing:" : @"\\uD83E\\uDD23", \
@":smiling_face_with_tear:" : @"\\uD83E\\uDD72", \
@":relaxed:" : @"☺️", \
@":blush:" : @"\\uD83D\\uDE0A", \
@":innocent:" : @"\\uD83D\\uDE07", \
@":slight_smile:" : @"\\uD83D\\uDE42", \
@":slightly_smiling_face:" : @"\\uD83D\\uDE42", \
@":upside_down:" : @"\\uD83D\\uDE43", \
@":upside_down_face:" : @"\\uD83D\\uDE43", \
@":wink:" : @"\\uD83D\\uDE09", \
@":relieved:" : @"\\uD83D\\uDE0C", \
@":heart_eyes:" : @"\\uD83D\\uDE0D", \
@":smiling_face_with_3_hearts:" : @"\\uD83E\\uDD70", \
@":kissing_heart:" : @"\\uD83D\\uDE18", \
@":kissing:" : @"\\uD83D\\uDE17", \
@":kissing_smiling_eyes:" : @"\\uD83D\\uDE19", \
@":kissing_closed_eyes:" : @"\\uD83D\\uDE1A", \
@":yum:" : @"\\uD83D\\uDE0B", \
@":stuck_out_tongue:" : @"\\uD83D\\uDE1B", \
@":stuck_out_tongue_closed_eyes:" : @"\\uD83D\\uDE1D", \
@":stuck_out_tongue_winking_eye:" : @"\\uD83D\\uDE1C", \
@":zany_face:" : @"\\uD83E\\uDD2A", \
@":face_with_raised_eyebrow:" : @"\\uD83E\\uDD28", \
@":face_with_monocle:" : @"\\uD83E\\uDDD0", \
@":nerd:" : @"\\uD83E\\uDD13", \
@":nerd_face:" : @"\\uD83E\\uDD13", \
@":sunglasses:" : @"\\uD83D\\uDE0E", \
@":disguised_face:" : @"\\uD83E\\uDD78", \
@":star_struck:" : @"\\uD83E\\uDD29", \
@":partying_face:" : @"\\uD83E\\uDD73", \
@":smirk:" : @"\\uD83D\\uDE0F", \
@":unamused:" : @"\\uD83D\\uDE12", \
@":disappointed:" : @"\\uD83D\\uDE1E", \
@":pensive:" : @"\\uD83D\\uDE14", \
@":worried:" : @"\\uD83D\\uDE1F", \
@":confused:" : @"\\uD83D\\uDE15", \
@":slight_frown:" : @"\\uD83D\\uDE41", \
@":slightly_frowning_face:" : @"\\uD83D\\uDE41", \
@":frowning2:" : @"☹️", \
@":white_frowning_face:" : @"☹️", \
@":persevere:" : @"\\uD83D\\uDE23", \
@":confounded:" : @"\\uD83D\\uDE16", \
@":tired_face:" : @"\\uD83D\\uDE2B", \
@":weary:" : @"\\uD83D\\uDE29", \
@":pleading_face:" : @"\\uD83E\\uDD7A", \
@":cry:" : @"\\uD83D\\uDE22", \
@":sob:" : @"\\uD83D\\uDE2D", \
@":triumph:" : @"\\uD83D\\uDE24", \
@":angry:" : @"\\uD83D\\uDE20", \
@":rage:" : @"\\uD83D\\uDE21", \
@":face_with_symbols_over_mouth:" : @"\\uD83E\\uDD2C", \
@":exploding_head:" : @"\\uD83E\\uDD2F", \
@":flushed:" : @"\\uD83D\\uDE33", \
@":hot_face:" : @"\\uD83E\\uDD75", \
@":cold_face:" : @"\\uD83E\\uDD76", \
@":face_in_clouds:" : @"\\uD83D\\uDE36‍\\uD83C\\uDF2B️", \
@":scream:" : @"\\uD83D\\uDE31", \
@":fearful:" : @"\\uD83D\\uDE28", \
@":cold_sweat:" : @"\\uD83D\\uDE30", \
@":disappointed_relieved:" : @"\\uD83D\\uDE25", \
@":sweat:" : @"\\uD83D\\uDE13", \
@":hugging:" : @"\\uD83E\\uDD17", \
@":hugging_face:" : @"\\uD83E\\uDD17", \
@":thinking:" : @"\\uD83E\\uDD14", \
@":thinking_face:" : @"\\uD83E\\uDD14", \
@":face_with_peeking_eye:" : @"\\uD83E\\uDEE3", \
@":face_with_hand_over_mouth:" : @"\\uD83E\\uDD2D", \
@":face_with_open_eyes_and_hand_over_mouth:" : @"\\uD83E\\uDEE2", \
@":saluting_face:" : @"\\uD83E\\uDEE1", \
@":shushing_face:" : @"\\uD83E\\uDD2B", \
@":melting_face:" : @"\\uD83E\\uDEE0", \
@":lying_face:" : @"\\uD83E\\uDD25", \
@":liar:" : @"\\uD83E\\uDD25", \
@":no_mouth:" : @"\\uD83D\\uDE36", \
@":dotted_line_face:" : @"\\uD83E\\uDEE5", \
@":neutral_face:" : @"\\uD83D\\uDE10", \
@":face_with_diagonal_mouth:" : @"\\uD83E\\uDEE4", \
@":expressionless:" : @"\\uD83D\\uDE11", \
@":grimacing:" : @"\\uD83D\\uDE2C", \
@":rolling_eyes:" : @"\\uD83D\\uDE44", \
@":face_with_rolling_eyes:" : @"\\uD83D\\uDE44", \
@":hushed:" : @"\\uD83D\\uDE2F", \
@":frowning:" : @"\\uD83D\\uDE26", \
@":anguished:" : @"\\uD83D\\uDE27", \
@":open_mouth:" : @"\\uD83D\\uDE2E", \
@":astonished:" : @"\\uD83D\\uDE32", \
@":yawning_face:" : @"\\uD83E\\uDD71", \
@":sleeping:" : @"\\uD83D\\uDE34", \
@":drooling_face:" : @"\\uD83E\\uDD24", \
@":drool:" : @"\\uD83E\\uDD24", \
@":sleepy:" : @"\\uD83D\\uDE2A", \
@":face_exhaling:" : @"\\uD83D\\uDE2E‍\\uD83D\\uDCA8", \
@":dizzy_face:" : @"\\uD83D\\uDE35", \
@":face_with_spiral_eyes:" : @"\\uD83D\\uDE35‍\\uD83D\\uDCAB", \
@":zipper_mouth:" : @"\\uD83E\\uDD10", \
@":zipper_mouth_face:" : @"\\uD83E\\uDD10", \
@":woozy_face:" : @"\\uD83E\\uDD74", \
@":nauseated_face:" : @"\\uD83E\\uDD22", \
@":sick:" : @"\\uD83E\\uDD22", \
@":face_vomiting:" : @"\\uD83E\\uDD2E", \
@":sneezing_face:" : @"\\uD83E\\uDD27", \
@":sneeze:" : @"\\uD83E\\uDD27", \
@":mask:" : @"\\uD83D\\uDE37", \
@":thermometer_face:" : @"\\uD83E\\uDD12", \
@":face_with_thermometer:" : @"\\uD83E\\uDD12", \
@":head_bandage:" : @"\\uD83E\\uDD15", \
@":face_with_head_bandage:" : @"\\uD83E\\uDD15", \
@":money_mouth:" : @"\\uD83E\\uDD11", \
@":money_mouth_face:" : @"\\uD83E\\uDD11", \
@":cowboy:" : @"\\uD83E\\uDD20", \
@":face_with_cowboy_hat:" : @"\\uD83E\\uDD20", \
@":smiling_imp:" : @"\\uD83D\\uDE08", \
@":imp:" : @"\\uD83D\\uDC7F", \
@":japanese_ogre:" : @"\\uD83D\\uDC79", \
@":japanese_goblin:" : @"\\uD83D\\uDC7A", \
@":clown:" : @"\\uD83E\\uDD21", \
@":clown_face:" : @"\\uD83E\\uDD21", \
@":poop:" : @"\\uD83D\\uDCA9", \
@":shit:" : @"\\uD83D\\uDCA9", \
@":hankey:" : @"\\uD83D\\uDCA9", \
@":poo:" : @"\\uD83D\\uDCA9", \
@":ghost:" : @"\\uD83D\\uDC7B", \
@":skull:" : @"\\uD83D\\uDC80", \
@":skeleton:" : @"\\uD83D\\uDC80", \
@":skull_crossbones:" : @"☠️", \
@":skull_and_crossbones:" : @"☠️", \
@":alien:" : @"\\uD83D\\uDC7D", \
@":space_invader:" : @"\\uD83D\\uDC7E", \
@":robot:" : @"\\uD83E\\uDD16", \
@":robot_face:" : @"\\uD83E\\uDD16", \
@":jack_o_lantern:" : @"\\uD83C\\uDF83", \
@":smiley_cat:" : @"\\uD83D\\uDE3A", \
@":smile_cat:" : @"\\uD83D\\uDE38", \
@":joy_cat:" : @"\\uD83D\\uDE39", \
@":heart_eyes_cat:" : @"\\uD83D\\uDE3B", \
@":smirk_cat:" : @"\\uD83D\\uDE3C", \
@":kissing_cat:" : @"\\uD83D\\uDE3D", \
@":scream_cat:" : @"\\uD83D\\uDE40", \
@":crying_cat_face:" : @"\\uD83D\\uDE3F", \
@":pouting_cat:" : @"\\uD83D\\uDE3E", \
@":heart_hands:" : @"\\uD83E\\uDEF6", \
@":palms_up_together:" : @"\\uD83E\\uDD32", \
@":open_hands:" : @"\\uD83D\\uDC50", \
@":raised_hands:" : @"\\uD83D\\uDE4C", \
@":clap:" : @"\\uD83D\\uDC4F", \
@":handshake:" : @"\\uD83E\\uDD1D", \
@":shaking_hands:" : @"\\uD83E\\uDD1D", \
@":thumbsup:" : @"\\uD83D\\uDC4D", \
@":+1:" : @"\\uD83D\\uDC4D", \
@":thumbup:" : @"\\uD83D\\uDC4D", \
@":thumbsdown:" : @"\\uD83D\\uDC4E", \
@":-1:" : @"\\uD83D\\uDC4E", \
@":thumbdown:" : @"\\uD83D\\uDC4E", \
@":punch:" : @"\\uD83D\\uDC4A", \
@":fist:" : @"✊", \
@":left_facing_fist:" : @"\\uD83E\\uDD1B", \
@":left_fist:" : @"\\uD83E\\uDD1B", \
@":right_facing_fist:" : @"\\uD83E\\uDD1C", \
@":right_fist:" : @"\\uD83E\\uDD1C", \
@":fingers_crossed:" : @"\\uD83E\\uDD1E", \
@":hand_with_index_and_middle_finger_crossed:" : @"\\uD83E\\uDD1E", \
@":v:" : @"✌️", \
@":hand_with_index_finger_and_thumb_crossed:" : @"\\uD83E\\uDEF0", \
@":love_you_gesture:" : @"\\uD83E\\uDD1F", \
@":metal:" : @"\\uD83E\\uDD18", \
@":sign_of_the_horns:" : @"\\uD83E\\uDD18", \
@":ok_hand:" : @"\\uD83D\\uDC4C", \
@":pinched_fingers:" : @"\\uD83E\\uDD0C", \
@":pinching_hand:" : @"\\uD83E\\uDD0F", \
@":palm_down_hand:" : @"\\uD83E\\uDEF3", \
@":palm_up_hand:" : @"\\uD83E\\uDEF4", \
@":point_left:" : @"\\uD83D\\uDC48", \
@":point_right:" : @"\\uD83D\\uDC49", \
@":point_up_2:" : @"\\uD83D\\uDC46", \
@":point_down:" : @"\\uD83D\\uDC47", \
@":point_up:" : @"☝️", \
@":raised_hand:" : @"✋", \
@":raised_back_of_hand:" : @"\\uD83E\\uDD1A", \
@":back_of_hand:" : @"\\uD83E\\uDD1A", \
@":hand_splayed:" : @"\\uD83D\\uDD90️", \
@":raised_hand_with_fingers_splayed:" : @"\\uD83D\\uDD90️", \
@":vulcan:" : @"\\uD83D\\uDD96", \
@":raised_hand_with_part_between_middle_and_ring_fingers:" : @"\\uD83D\\uDD96", \
@":wave:" : @"\\uD83D\\uDC4B", \
@":call_me:" : @"\\uD83E\\uDD19", \
@":call_me_hand:" : @"\\uD83E\\uDD19", \
@":leftwards_hand:" : @"\\uD83E\\uDEF2", \
@":rightwards_hand:" : @"\\uD83E\\uDEF1", \
@":muscle:" : @"\\uD83D\\uDCAA", \
@":mechanical_arm:" : @"\\uD83E\\uDDBE", \
@":middle_finger:" : @"\\uD83D\\uDD95", \
@":reversed_hand_with_middle_finger_extended:" : @"\\uD83D\\uDD95", \
@":writing_hand:" : @"✍️", \
@":pray:" : @"\\uD83D\\uDE4F", \
@":index_pointing_at_the_viewer:" : @"\\uD83E\\uDEF5", \
@":foot:" : @"\\uD83E\\uDDB6", \
@":leg:" : @"\\uD83E\\uDDB5", \
@":mechanical_leg:" : @"\\uD83E\\uDDBF", \
@":lipstick:" : @"\\uD83D\\uDC84", \
@":kiss:" : @"\\uD83D\\uDC8B", \
@":lips:" : @"\\uD83D\\uDC44", \
@":biting_lip:" : @"\\uD83E\\uDEE6", \
@":tooth:" : @"\\uD83E\\uDDB7", \
@":tongue:" : @"\\uD83D\\uDC45", \
@":ear:" : @"\\uD83D\\uDC42", \
@":ear_with_hearing_aid:" : @"\\uD83E\\uDDBB", \
@":nose:" : @"\\uD83D\\uDC43", \
@":footprints:" : @"\\uD83D\\uDC63", \
@":eye:" : @"\\uD83D\\uDC41️", \
@":eyes:" : @"\\uD83D\\uDC40", \
@":anatomical_heart:" : @"\\uD83E\\uDEC0", \
@":lungs:" : @"\\uD83E\\uDEC1", \
@":brain:" : @"\\uD83E\\uDDE0", \
@":speaking_head:" : @"\\uD83D\\uDDE3️", \
@":speaking_head_in_silhouette:" : @"\\uD83D\\uDDE3️", \
@":bust_in_silhouette:" : @"\\uD83D\\uDC64", \
@":busts_in_silhouette:" : @"\\uD83D\\uDC65", \
@":people_hugging:" : @"\\uD83E\\uDEC2", \
@":baby:" : @"\\uD83D\\uDC76", \
@":child:" : @"\\uD83E\\uDDD2", \
@":girl:" : @"\\uD83D\\uDC67", \
@":boy:" : @"\\uD83D\\uDC66", \
@":adult:" : @"\\uD83E\\uDDD1", \
@":woman:" : @"\\uD83D\\uDC69", \
@":man:" : @"\\uD83D\\uDC68", \
@":person_curly_hair:" : @"\\uD83E\\uDDD1‍\\uD83E\\uDDB1", \
@":woman_curly_haired:" : @"\\uD83D\\uDC69‍\\uD83E\\uDDB1", \
@":man_curly_haired:" : @"\\uD83D\\uDC68‍\\uD83E\\uDDB1", \
@":person_red_hair:" : @"\\uD83E\\uDDD1‍\\uD83E\\uDDB0", \
@":woman_red_haired:" : @"\\uD83D\\uDC69‍\\uD83E\\uDDB0", \
@":man_red_haired:" : @"\\uD83D\\uDC68‍\\uD83E\\uDDB0", \
@":blond_haired_person:" : @"\\uD83D\\uDC71", \
@":person_with_blond_hair:" : @"\\uD83D\\uDC71", \
@":blond_haired_woman:" : @"\\uD83D\\uDC71‍♀️", \
@":blond_haired_man:" : @"\\uD83D\\uDC71‍♂️", \
@":person_white_hair:" : @"\\uD83E\\uDDD1‍\\uD83E\\uDDB3", \
@":woman_white_haired:" : @"\\uD83D\\uDC69‍\\uD83E\\uDDB3", \
@":man_white_haired:" : @"\\uD83D\\uDC68‍\\uD83E\\uDDB3", \
@":person_bald:" : @"\\uD83E\\uDDD1‍\\uD83E\\uDDB2", \
@":woman_bald:" : @"\\uD83D\\uDC69‍\\uD83E\\uDDB2", \
@":man_bald:" : @"\\uD83D\\uDC68‍\\uD83E\\uDDB2", \
@":bearded_person:" : @"\\uD83E\\uDDD4", \
@":woman_beard:" : @"\\uD83E\\uDDD4‍♀️", \
@":man_beard:" : @"\\uD83E\\uDDD4‍♂️", \
@":older_adult:" : @"\\uD83E\\uDDD3", \
@":older_woman:" : @"\\uD83D\\uDC75", \
@":grandma:" : @"\\uD83D\\uDC75", \
@":older_man:" : @"\\uD83D\\uDC74", \
@":man_with_chinese_cap:" : @"\\uD83D\\uDC72", \
@":man_with_gua_pi_mao:" : @"\\uD83D\\uDC72", \
@":person_wearing_turban:" : @"\\uD83D\\uDC73", \
@":man_with_turban:" : @"\\uD83D\\uDC73", \
@":woman_wearing_turban:" : @"\\uD83D\\uDC73‍♀️", \
@":man_wearing_turban:" : @"\\uD83D\\uDC73‍♂️", \
@":woman_with_headscarf:" : @"\\uD83E\\uDDD5", \
@":police_officer:" : @"\\uD83D\\uDC6E", \
@":cop:" : @"\\uD83D\\uDC6E", \
@":woman_police_officer:" : @"\\uD83D\\uDC6E‍♀️", \
@":man_police_officer:" : @"\\uD83D\\uDC6E‍♂️", \
@":construction_worker:" : @"\\uD83D\\uDC77", \
@":woman_construction_worker:" : @"\\uD83D\\uDC77‍♀️", \
@":man_construction_worker:" : @"\\uD83D\\uDC77‍♂️", \
@":guard:" : @"\\uD83D\\uDC82", \
@":guardsman:" : @"\\uD83D\\uDC82", \
@":woman_guard:" : @"\\uD83D\\uDC82‍♀️", \
@":man_guard:" : @"\\uD83D\\uDC82‍♂️", \
@":detective:" : @"\\uD83D\\uDD75️", \
@":spy:" : @"\\uD83D\\uDD75️", \
@":sleuth_or_spy:" : @"\\uD83D\\uDD75️", \
@":woman_detective:" : @"\\uD83D\\uDD75️‍♀️", \
@":man_detective:" : @"\\uD83D\\uDD75️‍♂️", \
@":health_worker:" : @"\\uD83E\\uDDD1‍⚕️", \
@":woman_health_worker:" : @"\\uD83D\\uDC69‍⚕️", \
@":man_health_worker:" : @"\\uD83D\\uDC68‍⚕️", \
@":farmer:" : @"\\uD83E\\uDDD1‍\\uD83C\\uDF3E", \
@":woman_farmer:" : @"\\uD83D\\uDC69‍\\uD83C\\uDF3E", \
@":man_farmer:" : @"\\uD83D\\uDC68‍\\uD83C\\uDF3E", \
@":cook:" : @"\\uD83E\\uDDD1‍\\uD83C\\uDF73", \
@":woman_cook:" : @"\\uD83D\\uDC69‍\\uD83C\\uDF73", \
@":man_cook:" : @"\\uD83D\\uDC68‍\\uD83C\\uDF73", \
@":student:" : @"\\uD83E\\uDDD1‍\\uD83C\\uDF93", \
@":woman_student:" : @"\\uD83D\\uDC69‍\\uD83C\\uDF93", \
@":man_student:" : @"\\uD83D\\uDC68‍\\uD83C\\uDF93", \
@":singer:" : @"\\uD83E\\uDDD1‍\\uD83C\\uDFA4", \
@":woman_singer:" : @"\\uD83D\\uDC69‍\\uD83C\\uDFA4", \
@":man_singer:" : @"\\uD83D\\uDC68‍\\uD83C\\uDFA4", \
@":teacher:" : @"\\uD83E\\uDDD1‍\\uD83C\\uDFEB", \
@":woman_teacher:" : @"\\uD83D\\uDC69‍\\uD83C\\uDFEB", \
@":man_teacher:" : @"\\uD83D\\uDC68‍\\uD83C\\uDFEB", \
@":factory_worker:" : @"\\uD83E\\uDDD1‍\\uD83C\\uDFED", \
@":woman_factory_worker:" : @"\\uD83D\\uDC69‍\\uD83C\\uDFED", \
@":man_factory_worker:" : @"\\uD83D\\uDC68‍\\uD83C\\uDFED", \
@":technologist:" : @"\\uD83E\\uDDD1‍\\uD83D\\uDCBB", \
@":woman_technologist:" : @"\\uD83D\\uDC69‍\\uD83D\\uDCBB", \
@":man_technologist:" : @"\\uD83D\\uDC68‍\\uD83D\\uDCBB", \
@":office_worker:" : @"\\uD83E\\uDDD1‍\\uD83D\\uDCBC", \
@":woman_office_worker:" : @"\\uD83D\\uDC69‍\\uD83D\\uDCBC", \
@":man_office_worker:" : @"\\uD83D\\uDC68‍\\uD83D\\uDCBC", \
@":mechanic:" : @"\\uD83E\\uDDD1‍\\uD83D\\uDD27", \
@":woman_mechanic:" : @"\\uD83D\\uDC69‍\\uD83D\\uDD27", \
@":man_mechanic:" : @"\\uD83D\\uDC68‍\\uD83D\\uDD27", \
@":scientist:" : @"\\uD83E\\uDDD1‍\\uD83D\\uDD2C", \
@":woman_scientist:" : @"\\uD83D\\uDC69‍\\uD83D\\uDD2C", \
@":man_scientist:" : @"\\uD83D\\uDC68‍\\uD83D\\uDD2C", \
@":artist:" : @"\\uD83E\\uDDD1‍\\uD83C\\uDFA8", \
@":woman_artist:" : @"\\uD83D\\uDC69‍\\uD83C\\uDFA8", \
@":man_artist:" : @"\\uD83D\\uDC68‍\\uD83C\\uDFA8", \
@":firefighter:" : @"\\uD83E\\uDDD1‍\\uD83D\\uDE92", \
@":woman_firefighter:" : @"\\uD83D\\uDC69‍\\uD83D\\uDE92", \
@":man_firefighter:" : @"\\uD83D\\uDC68‍\\uD83D\\uDE92", \
@":pilot:" : @"\\uD83E\\uDDD1‍✈️", \
@":woman_pilot:" : @"\\uD83D\\uDC69‍✈️", \
@":man_pilot:" : @"\\uD83D\\uDC68‍✈️", \
@":astronaut:" : @"\\uD83E\\uDDD1‍\\uD83D\\uDE80", \
@":woman_astronaut:" : @"\\uD83D\\uDC69‍\\uD83D\\uDE80", \
@":man_astronaut:" : @"\\uD83D\\uDC68‍\\uD83D\\uDE80", \
@":judge:" : @"\\uD83E\\uDDD1‍⚖️", \
@":woman_judge:" : @"\\uD83D\\uDC69‍⚖️", \
@":man_judge:" : @"\\uD83D\\uDC68‍⚖️", \
@":person_with_veil:" : @"\\uD83D\\uDC70", \
@":woman_with_veil:" : @"\\uD83D\\uDC70‍♀️", \
@":bride_with_veil:" : @"\\uD83D\\uDC70‍♀️", \
@":man_with_veil:" : @"\\uD83D\\uDC70‍♂️", \
@":person_in_tuxedo:" : @"\\uD83E\\uDD35", \
@":woman_in_tuxedo:" : @"\\uD83E\\uDD35‍♀️", \
@":man_in_tuxedo:" : @"\\uD83E\\uDD35‍♂️", \
@":person_with_crown:" : @"\\uD83E\\uDEC5", \
@":princess:" : @"\\uD83D\\uDC78", \
@":prince:" : @"\\uD83E\\uDD34", \
@":superhero:" : @"\\uD83E\\uDDB8", \
@":woman_superhero:" : @"\\uD83E\\uDDB8‍♀️", \
@":man_superhero:" : @"\\uD83E\\uDDB8‍♂️", \
@":supervillain:" : @"\\uD83E\\uDDB9", \
@":woman_supervillain:" : @"\\uD83E\\uDDB9‍♀️", \
@":man_supervillain:" : @"\\uD83E\\uDDB9‍♂️", \
@":ninja:" : @"\\uD83E\\uDD77", \
@":mx_claus:" : @"\\uD83E\\uDDD1‍\\uD83C\\uDF84", \
@":mrs_claus:" : @"\\uD83E\\uDD36", \
@":mother_christmas:" : @"\\uD83E\\uDD36", \
@":santa:" : @"\\uD83C\\uDF85", \
@":mage:" : @"\\uD83E\\uDDD9", \
@":woman_mage:" : @"\\uD83E\\uDDD9‍♀️", \
@":man_mage:" : @"\\uD83E\\uDDD9‍♂️", \
@":elf:" : @"\\uD83E\\uDDDD", \
@":woman_elf:" : @"\\uD83E\\uDDDD‍♀️", \
@":man_elf:" : @"\\uD83E\\uDDDD‍♂️", \
@":troll:" : @"\\uD83E\\uDDCC", \
@":vampire:" : @"\\uD83E\\uDDDB", \
@":woman_vampire:" : @"\\uD83E\\uDDDB‍♀️", \
@":man_vampire:" : @"\\uD83E\\uDDDB‍♂️", \
@":zombie:" : @"\\uD83E\\uDDDF", \
@":woman_zombie:" : @"\\uD83E\\uDDDF‍♀️", \
@":man_zombie:" : @"\\uD83E\\uDDDF‍♂️", \
@":genie:" : @"\\uD83E\\uDDDE", \
@":woman_genie:" : @"\\uD83E\\uDDDE‍♀️", \
@":man_genie:" : @"\\uD83E\\uDDDE‍♂️", \
@":merperson:" : @"\\uD83E\\uDDDC", \
@":mermaid:" : @"\\uD83E\\uDDDC‍♀️", \
@":merman:" : @"\\uD83E\\uDDDC‍♂️", \
@":fairy:" : @"\\uD83E\\uDDDA", \
@":woman_fairy:" : @"\\uD83E\\uDDDA‍♀️", \
@":man_fairy:" : @"\\uD83E\\uDDDA‍♂️", \
@":angel:" : @"\\uD83D\\uDC7C", \
@":pregnant_person:" : @"\\uD83E\\uDEC4", \
@":pregnant_woman:" : @"\\uD83E\\uDD30", \
@":expecting_woman:" : @"\\uD83E\\uDD30", \
@":pregnant_man:" : @"\\uD83E\\uDEC3", \
@":breast_feeding:" : @"\\uD83E\\uDD31", \
@":person_feeding_baby:" : @"\\uD83E\\uDDD1‍\\uD83C\\uDF7C", \
@":woman_feeding_baby:" : @"\\uD83D\\uDC69‍\\uD83C\\uDF7C", \
@":man_feeding_baby:" : @"\\uD83D\\uDC68‍\\uD83C\\uDF7C", \
@":person_bowing:" : @"\\uD83D\\uDE47", \
@":bow:" : @"\\uD83D\\uDE47", \
@":woman_bowing:" : @"\\uD83D\\uDE47‍♀️", \
@":man_bowing:" : @"\\uD83D\\uDE47‍♂️", \
@":person_tipping_hand:" : @"\\uD83D\\uDC81", \
@":information_desk_person:" : @"\\uD83D\\uDC81", \
@":woman_tipping_hand:" : @"\\uD83D\\uDC81‍♀️", \
@":man_tipping_hand:" : @"\\uD83D\\uDC81‍♂️", \
@":person_gesturing_no:" : @"\\uD83D\\uDE45", \
@":no_good:" : @"\\uD83D\\uDE45", \
@":woman_gesturing_no:" : @"\\uD83D\\uDE45‍♀️", \
@":man_gesturing_no:" : @"\\uD83D\\uDE45‍♂️", \
@":person_gesturing_ok:" : @"\\uD83D\\uDE46", \
@":woman_gesturing_ok:" : @"\\uD83D\\uDE46‍♀️", \
@":man_gesturing_ok:" : @"\\uD83D\\uDE46‍♂️", \
@":person_raising_hand:" : @"\\uD83D\\uDE4B", \
@":raising_hand:" : @"\\uD83D\\uDE4B", \
@":woman_raising_hand:" : @"\\uD83D\\uDE4B‍♀️", \
@":man_raising_hand:" : @"\\uD83D\\uDE4B‍♂️", \
@":deaf_person:" : @"\\uD83E\\uDDCF", \
@":deaf_woman:" : @"\\uD83E\\uDDCF‍♀️", \
@":deaf_man:" : @"\\uD83E\\uDDCF‍♂️", \
@":person_facepalming:" : @"\\uD83E\\uDD26", \
@":face_palm:" : @"\\uD83E\\uDD26", \
@":facepalm:" : @"\\uD83E\\uDD26", \
@":woman_facepalming:" : @"\\uD83E\\uDD26‍♀️", \
@":man_facepalming:" : @"\\uD83E\\uDD26‍♂️", \
@":person_shrugging:" : @"\\uD83E\\uDD37", \
@":shrug:" : @"\\uD83E\\uDD37", \
@":woman_shrugging:" : @"\\uD83E\\uDD37‍♀️", \
@":man_shrugging:" : @"\\uD83E\\uDD37‍♂️", \
@":person_pouting:" : @"\\uD83D\\uDE4E", \
@":person_with_pouting_face:" : @"\\uD83D\\uDE4E", \
@":woman_pouting:" : @"\\uD83D\\uDE4E‍♀️", \
@":man_pouting:" : @"\\uD83D\\uDE4E‍♂️", \
@":person_frowning:" : @"\\uD83D\\uDE4D", \
@":woman_frowning:" : @"\\uD83D\\uDE4D‍♀️", \
@":man_frowning:" : @"\\uD83D\\uDE4D‍♂️", \
@":person_getting_haircut:" : @"\\uD83D\\uDC87", \
@":haircut:" : @"\\uD83D\\uDC87", \
@":woman_getting_haircut:" : @"\\uD83D\\uDC87‍♀️", \
@":man_getting_haircut:" : @"\\uD83D\\uDC87‍♂️", \
@":person_getting_massage:" : @"\\uD83D\\uDC86", \
@":massage:" : @"\\uD83D\\uDC86", \
@":woman_getting_face_massage:" : @"\\uD83D\\uDC86‍♀️", \
@":man_getting_face_massage:" : @"\\uD83D\\uDC86‍♂️", \
@":person_in_steamy_room:" : @"\\uD83E\\uDDD6", \
@":woman_in_steamy_room:" : @"\\uD83E\\uDDD6‍♀️", \
@":man_in_steamy_room:" : @"\\uD83E\\uDDD6‍♂️", \
@":nail_care:" : @"\\uD83D\\uDC85", \
@":selfie:" : @"\\uD83E\\uDD33", \
@":dancer:" : @"\\uD83D\\uDC83", \
@":man_dancing:" : @"\\uD83D\\uDD7A", \
@":male_dancer:" : @"\\uD83D\\uDD7A", \
@":people_with_bunny_ears_partying:" : @"\\uD83D\\uDC6F", \
@":dancers:" : @"\\uD83D\\uDC6F", \
@":women_with_bunny_ears_partying:" : @"\\uD83D\\uDC6F‍♀️", \
@":men_with_bunny_ears_partying:" : @"\\uD83D\\uDC6F‍♂️", \
@":levitate:" : @"\\uD83D\\uDD74️", \
@":man_in_business_suit_levitating:" : @"\\uD83D\\uDD74️", \
@":person_in_manual_wheelchair:" : @"\\uD83E\\uDDD1‍\\uD83E\\uDDBD", \
@":woman_in_manual_wheelchair:" : @"\\uD83D\\uDC69‍\\uD83E\\uDDBD", \
@":man_in_manual_wheelchair:" : @"\\uD83D\\uDC68‍\\uD83E\\uDDBD", \
@":person_in_motorized_wheelchair:" : @"\\uD83E\\uDDD1‍\\uD83E\\uDDBC", \
@":woman_in_motorized_wheelchair:" : @"\\uD83D\\uDC69‍\\uD83E\\uDDBC", \
@":man_in_motorized_wheelchair:" : @"\\uD83D\\uDC68‍\\uD83E\\uDDBC", \
@":person_walking:" : @"\\uD83D\\uDEB6", \
@":walking:" : @"\\uD83D\\uDEB6", \
@":woman_walking:" : @"\\uD83D\\uDEB6‍♀️", \
@":man_walking:" : @"\\uD83D\\uDEB6‍♂️", \
@":person_with_probing_cane:" : @"\\uD83E\\uDDD1‍\\uD83E\\uDDAF", \
@":woman_with_probing_cane:" : @"\\uD83D\\uDC69‍\\uD83E\\uDDAF", \
@":man_with_probing_cane:" : @"\\uD83D\\uDC68‍\\uD83E\\uDDAF", \
@":person_kneeling:" : @"\\uD83E\\uDDCE", \
@":woman_kneeling:" : @"\\uD83E\\uDDCE‍♀️", \
@":man_kneeling:" : @"\\uD83E\\uDDCE‍♂️", \
@":person_running:" : @"\\uD83C\\uDFC3", \
@":runner:" : @"\\uD83C\\uDFC3", \
@":woman_running:" : @"\\uD83C\\uDFC3‍♀️", \
@":man_running:" : @"\\uD83C\\uDFC3‍♂️", \
@":person_standing:" : @"\\uD83E\\uDDCD", \
@":woman_standing:" : @"\\uD83E\\uDDCD‍♀️", \
@":man_standing:" : @"\\uD83E\\uDDCD‍♂️", \
@":people_holding_hands:" : @"\\uD83E\\uDDD1‍\\uD83E\\uDD1D‍\\uD83E\\uDDD1", \
@":couple:" : @"\\uD83D\\uDC6B", \
@":two_women_holding_hands:" : @"\\uD83D\\uDC6D", \
@":two_men_holding_hands:" : @"\\uD83D\\uDC6C", \
@":couple_with_heart:" : @"\\uD83D\\uDC91", \
@":couple_with_heart_woman_man:" : @"\\uD83D\\uDC69‍❤️‍\\uD83D\\uDC68", \
@":couple_ww:" : @"\\uD83D\\uDC69‍❤️‍\\uD83D\\uDC69", \
@":couple_with_heart_ww:" : @"\\uD83D\\uDC69‍❤️‍\\uD83D\\uDC69", \
@":couple_mm:" : @"\\uD83D\\uDC68‍❤️‍\\uD83D\\uDC68", \
@":couple_with_heart_mm:" : @"\\uD83D\\uDC68‍❤️‍\\uD83D\\uDC68", \
@":couplekiss:" : @"\\uD83D\\uDC8F", \
@":kiss_woman_man:" : @"\\uD83D\\uDC69‍❤️‍\\uD83D\\uDC8B‍\\uD83D\\uDC68", \
@":kiss_ww:" : @"\\uD83D\\uDC69‍❤️‍\\uD83D\\uDC8B‍\\uD83D\\uDC69", \
@":couplekiss_ww:" : @"\\uD83D\\uDC69‍❤️‍\\uD83D\\uDC8B‍\\uD83D\\uDC69", \
@":kiss_mm:" : @"\\uD83D\\uDC68‍❤️‍\\uD83D\\uDC8B‍\\uD83D\\uDC68", \
@":couplekiss_mm:" : @"\\uD83D\\uDC68‍❤️‍\\uD83D\\uDC8B‍\\uD83D\\uDC68", \
@":family:" : @"\\uD83D\\uDC6A", \
@":family_man_woman_boy:" : @"\\uD83D\\uDC68‍\\uD83D\\uDC69‍\\uD83D\\uDC66", \
@":family_mwg:" : @"\\uD83D\\uDC68‍\\uD83D\\uDC69‍\\uD83D\\uDC67", \
@":family_mwgb:" : @"\\uD83D\\uDC68‍\\uD83D\\uDC69‍\\uD83D\\uDC67‍\\uD83D\\uDC66", \
@":family_mwbb:" : @"\\uD83D\\uDC68‍\\uD83D\\uDC69‍\\uD83D\\uDC66‍\\uD83D\\uDC66", \
@":family_mwgg:" : @"\\uD83D\\uDC68‍\\uD83D\\uDC69‍\\uD83D\\uDC67‍\\uD83D\\uDC67", \
@":family_wwb:" : @"\\uD83D\\uDC69‍\\uD83D\\uDC69‍\\uD83D\\uDC66", \
@":family_wwg:" : @"\\uD83D\\uDC69‍\\uD83D\\uDC69‍\\uD83D\\uDC67", \
@":family_wwgb:" : @"\\uD83D\\uDC69‍\\uD83D\\uDC69‍\\uD83D\\uDC67‍\\uD83D\\uDC66", \
@":family_wwbb:" : @"\\uD83D\\uDC69‍\\uD83D\\uDC69‍\\uD83D\\uDC66‍\\uD83D\\uDC66", \
@":family_wwgg:" : @"\\uD83D\\uDC69‍\\uD83D\\uDC69‍\\uD83D\\uDC67‍\\uD83D\\uDC67", \
@":family_mmb:" : @"\\uD83D\\uDC68‍\\uD83D\\uDC68‍\\uD83D\\uDC66", \
@":family_mmg:" : @"\\uD83D\\uDC68‍\\uD83D\\uDC68‍\\uD83D\\uDC67", \
@":family_mmgb:" : @"\\uD83D\\uDC68‍\\uD83D\\uDC68‍\\uD83D\\uDC67‍\\uD83D\\uDC66", \
@":family_mmbb:" : @"\\uD83D\\uDC68‍\\uD83D\\uDC68‍\\uD83D\\uDC66‍\\uD83D\\uDC66", \
@":family_mmgg:" : @"\\uD83D\\uDC68‍\\uD83D\\uDC68‍\\uD83D\\uDC67‍\\uD83D\\uDC67", \
@":family_woman_boy:" : @"\\uD83D\\uDC69‍\\uD83D\\uDC66", \
@":family_woman_girl:" : @"\\uD83D\\uDC69‍\\uD83D\\uDC67", \
@":family_woman_girl_boy:" : @"\\uD83D\\uDC69‍\\uD83D\\uDC67‍\\uD83D\\uDC66", \
@":family_woman_boy_boy:" : @"\\uD83D\\uDC69‍\\uD83D\\uDC66‍\\uD83D\\uDC66", \
@":family_woman_girl_girl:" : @"\\uD83D\\uDC69‍\\uD83D\\uDC67‍\\uD83D\\uDC67", \
@":family_man_boy:" : @"\\uD83D\\uDC68‍\\uD83D\\uDC66", \
@":family_man_girl:" : @"\\uD83D\\uDC68‍\\uD83D\\uDC67", \
@":family_man_girl_boy:" : @"\\uD83D\\uDC68‍\\uD83D\\uDC67‍\\uD83D\\uDC66", \
@":family_man_boy_boy:" : @"\\uD83D\\uDC68‍\\uD83D\\uDC66‍\\uD83D\\uDC66", \
@":family_man_girl_girl:" : @"\\uD83D\\uDC68‍\\uD83D\\uDC67‍\\uD83D\\uDC67", \
@":knot:" : @"\\uD83E\\uDEA2", \
@":yarn:" : @"\\uD83E\\uDDF6", \
@":thread:" : @"\\uD83E\\uDDF5", \
@":sewing_needle:" : @"\\uD83E\\uDEA1", \
@":coat:" : @"\\uD83E\\uDDE5", \
@":lab_coat:" : @"\\uD83E\\uDD7C", \
@":safety_vest:" : @"\\uD83E\\uDDBA", \
@":womans_clothes:" : @"\\uD83D\\uDC5A", \
@":shirt:" : @"\\uD83D\\uDC55", \
@":jeans:" : @"\\uD83D\\uDC56", \
@":briefs:" : @"\\uD83E\\uDE72", \
@":shorts:" : @"\\uD83E\\uDE73", \
@":necktie:" : @"\\uD83D\\uDC54", \
@":dress:" : @"\\uD83D\\uDC57", \
@":bikini:" : @"\\uD83D\\uDC59", \
@":one_piece_swimsuit:" : @"\\uD83E\\uDE71", \
@":kimono:" : @"\\uD83D\\uDC58", \
@":sari:" : @"\\uD83E\\uDD7B", \
@":thong_sandal:" : @"\\uD83E\\uDE74", \
@":womans_flat_shoe:" : @"\\uD83E\\uDD7F", \
@":high_heel:" : @"\\uD83D\\uDC60", \
@":sandal:" : @"\\uD83D\\uDC61", \
@":boot:" : @"\\uD83D\\uDC62", \
@":mans_shoe:" : @"\\uD83D\\uDC5E", \
@":athletic_shoe:" : @"\\uD83D\\uDC5F", \
@":hiking_boot:" : @"\\uD83E\\uDD7E", \
@":socks:" : @"\\uD83E\\uDDE6", \
@":gloves:" : @"\\uD83E\\uDDE4", \
@":scarf:" : @"\\uD83E\\uDDE3", \
@":tophat:" : @"\\uD83C\\uDFA9", \
@":billed_cap:" : @"\\uD83E\\uDDE2", \
@":womans_hat:" : @"\\uD83D\\uDC52", \
@":mortar_board:" : @"\\uD83C\\uDF93", \
@":helmet_with_cross:" : @"⛑️", \
@":helmet_with_white_cross:" : @"⛑️", \
@":military_helmet:" : @"\\uD83E\\uDE96", \
@":crown:" : @"\\uD83D\\uDC51", \
@":ring:" : @"\\uD83D\\uDC8D", \
@":pouch:" : @"\\uD83D\\uDC5D", \
@":purse:" : @"\\uD83D\\uDC5B", \
@":handbag:" : @"\\uD83D\\uDC5C", \
@":briefcase:" : @"\\uD83D\\uDCBC", \
@":school_satchel:" : @"\\uD83C\\uDF92", \
@":luggage:" : @"\\uD83E\\uDDF3", \
@":eyeglasses:" : @"\\uD83D\\uDC53", \
@":dark_sunglasses:" : @"\\uD83D\\uDD76️", \
@":goggles:" : @"\\uD83E\\uDD7D", \
@":closed_umbrella:" : @"\\uD83C\\uDF02", \
@":dog:" : @"\\uD83D\\uDC36", \
@":cat:" : @"\\uD83D\\uDC31", \
@":mouse:" : @"\\uD83D\\uDC2D", \
@":hamster:" : @"\\uD83D\\uDC39", \
@":rabbit:" : @"\\uD83D\\uDC30", \
@":fox:" : @"\\uD83E\\uDD8A", \
@":fox_face:" : @"\\uD83E\\uDD8A", \
@":bear:" : @"\\uD83D\\uDC3B", \
@":panda_face:" : @"\\uD83D\\uDC3C", \
@":polar_bear:" : @"\\uD83D\\uDC3B‍❄️", \
@":koala:" : @"\\uD83D\\uDC28", \
@":tiger:" : @"\\uD83D\\uDC2F", \
@":lion_face:" : @"\\uD83E\\uDD81", \
@":lion:" : @"\\uD83E\\uDD81", \
@":cow:" : @"\\uD83D\\uDC2E", \
@":pig:" : @"\\uD83D\\uDC37", \
@":pig_nose:" : @"\\uD83D\\uDC3D", \
@":frog:" : @"\\uD83D\\uDC38", \
@":monkey_face:" : @"\\uD83D\\uDC35", \
@":see_no_evil:" : @"\\uD83D\\uDE48", \
@":hear_no_evil:" : @"\\uD83D\\uDE49", \
@":speak_no_evil:" : @"\\uD83D\\uDE4A", \
@":monkey:" : @"\\uD83D\\uDC12", \
@":chicken:" : @"\\uD83D\\uDC14", \
@":penguin:" : @"\\uD83D\\uDC27", \
@":bird:" : @"\\uD83D\\uDC26", \
@":baby_chick:" : @"\\uD83D\\uDC24", \
@":hatching_chick:" : @"\\uD83D\\uDC23", \
@":hatched_chick:" : @"\\uD83D\\uDC25", \
@":duck:" : @"\\uD83E\\uDD86", \
@":eagle:" : @"\\uD83E\\uDD85", \
@":owl:" : @"\\uD83E\\uDD89", \
@":bat:" : @"\\uD83E\\uDD87", \
@":wolf:" : @"\\uD83D\\uDC3A", \
@":boar:" : @"\\uD83D\\uDC17", \
@":horse:" : @"\\uD83D\\uDC34", \
@":unicorn:" : @"\\uD83E\\uDD84", \
@":unicorn_face:" : @"\\uD83E\\uDD84", \
@":bee:" : @"\\uD83D\\uDC1D", \
@":bug:" : @"\\uD83D\\uDC1B", \
@":butterfly:" : @"\\uD83E\\uDD8B", \
@":snail:" : @"\\uD83D\\uDC0C", \
@":worm:" : @"\\uD83E\\uDEB1", \
@":lady_beetle:" : @"\\uD83D\\uDC1E", \
@":ant:" : @"\\uD83D\\uDC1C", \
@":fly:" : @"\\uD83E\\uDEB0", \
@":mosquito:" : @"\\uD83E\\uDD9F", \
@":cockroach:" : @"\\uD83E\\uDEB3", \
@":beetle:" : @"\\uD83E\\uDEB2", \
@":cricket:" : @"\\uD83E\\uDD97", \
@":spider:" : @"\\uD83D\\uDD77️", \
@":spider_web:" : @"\\uD83D\\uDD78️", \
@":scorpion:" : @"\\uD83E\\uDD82", \
@":turtle:" : @"\\uD83D\\uDC22", \
@":snake:" : @"\\uD83D\\uDC0D", \
@":lizard:" : @"\\uD83E\\uDD8E", \
@":t_rex:" : @"\\uD83E\\uDD96", \
@":sauropod:" : @"\\uD83E\\uDD95", \
@":octopus:" : @"\\uD83D\\uDC19", \
@":squid:" : @"\\uD83E\\uDD91", \
@":shrimp:" : @"\\uD83E\\uDD90", \
@":lobster:" : @"\\uD83E\\uDD9E", \
@":crab:" : @"\\uD83E\\uDD80", \
@":blowfish:" : @"\\uD83D\\uDC21", \
@":tropical_fish:" : @"\\uD83D\\uDC20", \
@":fish:" : @"\\uD83D\\uDC1F", \
@":seal:" : @"\\uD83E\\uDDAD", \
@":dolphin:" : @"\\uD83D\\uDC2C", \
@":whale:" : @"\\uD83D\\uDC33", \
@":whale2:" : @"\\uD83D\\uDC0B", \
@":shark:" : @"\\uD83E\\uDD88", \
@":crocodile:" : @"\\uD83D\\uDC0A", \
@":tiger2:" : @"\\uD83D\\uDC05", \
@":leopard:" : @"\\uD83D\\uDC06", \
@":zebra:" : @"\\uD83E\\uDD93", \
@":gorilla:" : @"\\uD83E\\uDD8D", \
@":orangutan:" : @"\\uD83E\\uDDA7", \
@":elephant:" : @"\\uD83D\\uDC18", \
@":mammoth:" : @"\\uD83E\\uDDA3", \
@":bison:" : @"\\uD83E\\uDDAC", \
@":hippopotamus:" : @"\\uD83E\\uDD9B", \
@":rhino:" : @"\\uD83E\\uDD8F", \
@":rhinoceros:" : @"\\uD83E\\uDD8F", \
@":dromedary_camel:" : @"\\uD83D\\uDC2A", \
@":camel:" : @"\\uD83D\\uDC2B", \
@":giraffe:" : @"\\uD83E\\uDD92", \
@":kangaroo:" : @"\\uD83E\\uDD98", \
@":water_buffalo:" : @"\\uD83D\\uDC03", \
@":ox:" : @"\\uD83D\\uDC02", \
@":cow2:" : @"\\uD83D\\uDC04", \
@":racehorse:" : @"\\uD83D\\uDC0E", \
@":pig2:" : @"\\uD83D\\uDC16", \
@":ram:" : @"\\uD83D\\uDC0F", \
@":sheep:" : @"\\uD83D\\uDC11", \
@":llama:" : @"\\uD83E\\uDD99", \
@":goat:" : @"\\uD83D\\uDC10", \
@":deer:" : @"\\uD83E\\uDD8C", \
@":dog2:" : @"\\uD83D\\uDC15", \
@":poodle:" : @"\\uD83D\\uDC29", \
@":guide_dog:" : @"\\uD83E\\uDDAE", \
@":service_dog:" : @"\\uD83D\\uDC15‍\\uD83E\\uDDBA", \
@":cat2:" : @"\\uD83D\\uDC08", \
@":black_cat:" : @"\\uD83D\\uDC08‍⬛", \
@":feather:" : @"\\uD83E\\uDEB6", \
@":rooster:" : @"\\uD83D\\uDC13", \
@":turkey:" : @"\\uD83E\\uDD83", \
@":dodo:" : @"\\uD83E\\uDDA4", \
@":peacock:" : @"\\uD83E\\uDD9A", \
@":parrot:" : @"\\uD83E\\uDD9C", \
@":swan:" : @"\\uD83E\\uDDA2", \
@":flamingo:" : @"\\uD83E\\uDDA9", \
@":dove:" : @"\\uD83D\\uDD4A️", \
@":dove_of_peace:" : @"\\uD83D\\uDD4A️", \
@":rabbit2:" : @"\\uD83D\\uDC07", \
@":raccoon:" : @"\\uD83E\\uDD9D", \
@":skunk:" : @"\\uD83E\\uDDA8", \
@":badger:" : @"\\uD83E\\uDDA1", \
@":beaver:" : @"\\uD83E\\uDDAB", \
@":otter:" : @"\\uD83E\\uDDA6", \
@":sloth:" : @"\\uD83E\\uDDA5", \
@":mouse2:" : @"\\uD83D\\uDC01", \
@":rat:" : @"\\uD83D\\uDC00", \
@":chipmunk:" : @"\\uD83D\\uDC3F️", \
@":hedgehog:" : @"\\uD83E\\uDD94", \
@":feet:" : @"\\uD83D\\uDC3E", \
@":paw_prints:" : @"\\uD83D\\uDC3E", \
@":dragon:" : @"\\uD83D\\uDC09", \
@":dragon_face:" : @"\\uD83D\\uDC32", \
@":cactus:" : @"\\uD83C\\uDF35", \
@":christmas_tree:" : @"\\uD83C\\uDF84", \
@":evergreen_tree:" : @"\\uD83C\\uDF32", \
@":deciduous_tree:" : @"\\uD83C\\uDF33", \
@":palm_tree:" : @"\\uD83C\\uDF34", \
@":seedling:" : @"\\uD83C\\uDF31", \
@":herb:" : @"\\uD83C\\uDF3F", \
@":shamrock:" : @"☘️", \
@":four_leaf_clover:" : @"\\uD83C\\uDF40", \
@":bamboo:" : @"\\uD83C\\uDF8D", \
@":tanabata_tree:" : @"\\uD83C\\uDF8B", \
@":leaves:" : @"\\uD83C\\uDF43", \
@":fallen_leaf:" : @"\\uD83C\\uDF42", \
@":maple_leaf:" : @"\\uD83C\\uDF41", \
@":empty_nest:" : @"\\uD83E\\uDEB9", \
@":nest_with_eggs:" : @"\\uD83E\\uDEBA", \
@":mushroom:" : @"\\uD83C\\uDF44", \
@":shell:" : @"\\uD83D\\uDC1A", \
@":coral:" : @"\\uD83E\\uDEB8", \
@":rock:" : @"\\uD83E\\uDEA8", \
@":wood:" : @"\\uD83E\\uDEB5", \
@":ear_of_rice:" : @"\\uD83C\\uDF3E", \
@":potted_plant:" : @"\\uD83E\\uDEB4", \
@":bouquet:" : @"\\uD83D\\uDC90", \
@":tulip:" : @"\\uD83C\\uDF37", \
@":rose:" : @"\\uD83C\\uDF39", \
@":wilted_rose:" : @"\\uD83E\\uDD40", \
@":wilted_flower:" : @"\\uD83E\\uDD40", \
@":lotus:" : @"\\uD83E\\uDEB7", \
@":hibiscus:" : @"\\uD83C\\uDF3A", \
@":cherry_blossom:" : @"\\uD83C\\uDF38", \
@":blossom:" : @"\\uD83C\\uDF3C", \
@":sunflower:" : @"\\uD83C\\uDF3B", \
@":sun_with_face:" : @"\\uD83C\\uDF1E", \
@":full_moon_with_face:" : @"\\uD83C\\uDF1D", \
@":first_quarter_moon_with_face:" : @"\\uD83C\\uDF1B", \
@":last_quarter_moon_with_face:" : @"\\uD83C\\uDF1C", \
@":new_moon_with_face:" : @"\\uD83C\\uDF1A", \
@":full_moon:" : @"\\uD83C\\uDF15", \
@":waning_gibbous_moon:" : @"\\uD83C\\uDF16", \
@":last_quarter_moon:" : @"\\uD83C\\uDF17", \
@":waning_crescent_moon:" : @"\\uD83C\\uDF18", \
@":new_moon:" : @"\\uD83C\\uDF11", \
@":waxing_crescent_moon:" : @"\\uD83C\\uDF12", \
@":first_quarter_moon:" : @"\\uD83C\\uDF13", \
@":waxing_gibbous_moon:" : @"\\uD83C\\uDF14", \
@":crescent_moon:" : @"\\uD83C\\uDF19", \
@":earth_americas:" : @"\\uD83C\\uDF0E", \
@":earth_africa:" : @"\\uD83C\\uDF0D", \
@":earth_asia:" : @"\\uD83C\\uDF0F", \
@":ringed_planet:" : @"\\uD83E\\uDE90", \
@":dizzy:" : @"\\uD83D\\uDCAB", \
@":star:" : @"⭐", \
@":star2:" : @"\\uD83C\\uDF1F", \
@":sparkles:" : @"✨", \
@":zap:" : @"⚡", \
@":comet:" : @"☄️", \
@":boom:" : @"\\uD83D\\uDCA5", \
@":fire:" : @"\\uD83D\\uDD25", \
@":flame:" : @"\\uD83D\\uDD25", \
@":cloud_tornado:" : @"\\uD83C\\uDF2A️", \
@":cloud_with_tornado:" : @"\\uD83C\\uDF2A️", \
@":rainbow:" : @"\\uD83C\\uDF08", \
@":sunny:" : @"☀️", \
@":white_sun_small_cloud:" : @"\\uD83C\\uDF24️", \
@":white_sun_with_small_cloud:" : @"\\uD83C\\uDF24️", \
@":partly_sunny:" : @"⛅", \
@":white_sun_cloud:" : @"\\uD83C\\uDF25️", \
@":white_sun_behind_cloud:" : @"\\uD83C\\uDF25️", \
@":cloud:" : @"☁️", \
@":white_sun_rain_cloud:" : @"\\uD83C\\uDF26️", \
@":white_sun_behind_cloud_with_rain:" : @"\\uD83C\\uDF26️", \
@":cloud_rain:" : @"\\uD83C\\uDF27️", \
@":cloud_with_rain:" : @"\\uD83C\\uDF27️", \
@":thunder_cloud_rain:" : @"⛈️", \
@":thunder_cloud_and_rain:" : @"⛈️", \
@":cloud_lightning:" : @"\\uD83C\\uDF29️", \
@":cloud_with_lightning:" : @"\\uD83C\\uDF29️", \
@":cloud_snow:" : @"\\uD83C\\uDF28️", \
@":cloud_with_snow:" : @"\\uD83C\\uDF28️", \
@":snowflake:" : @"❄️", \
@":snowman2:" : @"☃️", \
@":snowman:" : @"⛄", \
@":wind_blowing_face:" : @"\\uD83C\\uDF2C️", \
@":dash:" : @"\\uD83D\\uDCA8", \
@":droplet:" : @"\\uD83D\\uDCA7", \
@":sweat_drops:" : @"\\uD83D\\uDCA6", \
@":bubbles:" : @"\\uD83E\\uDEE7", \
@":umbrella:" : @"☔", \
@":umbrella2:" : @"☂️", \
@":ocean:" : @"\\uD83C\\uDF0A", \
@":fog:" : @"\\uD83C\\uDF2B️", \
@":green_apple:" : @"\\uD83C\\uDF4F", \
@":apple:" : @"\\uD83C\\uDF4E", \
@":pear:" : @"\\uD83C\\uDF50", \
@":tangerine:" : @"\\uD83C\\uDF4A", \
@":lemon:" : @"\\uD83C\\uDF4B", \
@":banana:" : @"\\uD83C\\uDF4C", \
@":watermelon:" : @"\\uD83C\\uDF49", \
@":grapes:" : @"\\uD83C\\uDF47", \
@":blueberries:" : @"\\uD83E\\uDED0", \
@":strawberry:" : @"\\uD83C\\uDF53", \
@":melon:" : @"\\uD83C\\uDF48", \
@":cherries:" : @"\\uD83C\\uDF52", \
@":peach:" : @"\\uD83C\\uDF51", \
@":mango:" : @"\\uD83E\\uDD6D", \
@":pineapple:" : @"\\uD83C\\uDF4D", \
@":coconut:" : @"\\uD83E\\uDD65", \
@":kiwi:" : @"\\uD83E\\uDD5D", \
@":kiwifruit:" : @"\\uD83E\\uDD5D", \
@":tomato:" : @"\\uD83C\\uDF45", \
@":eggplant:" : @"\\uD83C\\uDF46", \
@":avocado:" : @"\\uD83E\\uDD51", \
@":olive:" : @"\\uD83E\\uDED2", \
@":broccoli:" : @"\\uD83E\\uDD66", \
@":leafy_green:" : @"\\uD83E\\uDD6C", \
@":bell_pepper:" : @"\\uD83E\\uDED1", \
@":cucumber:" : @"\\uD83E\\uDD52", \
@":hot_pepper:" : @"\\uD83C\\uDF36️", \
@":corn:" : @"\\uD83C\\uDF3D", \
@":carrot:" : @"\\uD83E\\uDD55", \
@":garlic:" : @"\\uD83E\\uDDC4", \
@":onion:" : @"\\uD83E\\uDDC5", \
@":potato:" : @"\\uD83E\\uDD54", \
@":sweet_potato:" : @"\\uD83C\\uDF60", \
@":croissant:" : @"\\uD83E\\uDD50", \
@":bagel:" : @"\\uD83E\\uDD6F", \
@":bread:" : @"\\uD83C\\uDF5E", \
@":french_bread:" : @"\\uD83E\\uDD56", \
@":baguette_bread:" : @"\\uD83E\\uDD56", \
@":flatbread:" : @"\\uD83E\\uDED3", \
@":pretzel:" : @"\\uD83E\\uDD68", \
@":cheese:" : @"\\uD83E\\uDDC0", \
@":cheese_wedge:" : @"\\uD83E\\uDDC0", \
@":egg:" : @"\\uD83E\\uDD5A", \
@":cooking:" : @"\\uD83C\\uDF73", \
@":butter:" : @"\\uD83E\\uDDC8", \
@":pancakes:" : @"\\uD83E\\uDD5E", \
@":waffle:" : @"\\uD83E\\uDDC7", \
@":bacon:" : @"\\uD83E\\uDD53", \
@":cut_of_meat:" : @"\\uD83E\\uDD69", \
@":poultry_leg:" : @"\\uD83C\\uDF57", \
@":meat_on_bone:" : @"\\uD83C\\uDF56", \
@":bone:" : @"\\uD83E\\uDDB4", \
@":hotdog:" : @"\\uD83C\\uDF2D", \
@":hot_dog:" : @"\\uD83C\\uDF2D", \
@":hamburger:" : @"\\uD83C\\uDF54", \
@":fries:" : @"\\uD83C\\uDF5F", \
@":pizza:" : @"\\uD83C\\uDF55", \
@":sandwich:" : @"\\uD83E\\uDD6A", \
@":stuffed_flatbread:" : @"\\uD83E\\uDD59", \
@":stuffed_pita:" : @"\\uD83E\\uDD59", \
@":falafel:" : @"\\uD83E\\uDDC6", \
@":taco:" : @"\\uD83C\\uDF2E", \
@":burrito:" : @"\\uD83C\\uDF2F", \
@":tamale:" : @"\\uD83E\\uDED4", \
@":salad:" : @"\\uD83E\\uDD57", \
@":green_salad:" : @"\\uD83E\\uDD57", \
@":shallow_pan_of_food:" : @"\\uD83E\\uDD58", \
@":paella:" : @"\\uD83E\\uDD58", \
@":fondue:" : @"\\uD83E\\uDED5", \
@":canned_food:" : @"\\uD83E\\uDD6B", \
@":jar:" : @"\\uD83E\\uDED9", \
@":spaghetti:" : @"\\uD83C\\uDF5D", \
@":ramen:" : @"\\uD83C\\uDF5C", \
@":stew:" : @"\\uD83C\\uDF72", \
@":curry:" : @"\\uD83C\\uDF5B", \
@":sushi:" : @"\\uD83C\\uDF63", \
@":bento:" : @"\\uD83C\\uDF71", \
@":dumpling:" : @"\\uD83E\\uDD5F", \
@":oyster:" : @"\\uD83E\\uDDAA", \
@":fried_shrimp:" : @"\\uD83C\\uDF64", \
@":rice_ball:" : @"\\uD83C\\uDF59", \
@":rice:" : @"\\uD83C\\uDF5A", \
@":rice_cracker:" : @"\\uD83C\\uDF58", \
@":fish_cake:" : @"\\uD83C\\uDF65", \
@":fortune_cookie:" : @"\\uD83E\\uDD60", \
@":moon_cake:" : @"\\uD83E\\uDD6E", \
@":oden:" : @"\\uD83C\\uDF62", \
@":dango:" : @"\\uD83C\\uDF61", \
@":shaved_ice:" : @"\\uD83C\\uDF67", \
@":ice_cream:" : @"\\uD83C\\uDF68", \
@":icecream:" : @"\\uD83C\\uDF66", \
@":pie:" : @"\\uD83E\\uDD67", \
@":cupcake:" : @"\\uD83E\\uDDC1", \
@":cake:" : @"\\uD83C\\uDF70", \
@":birthday:" : @"\\uD83C\\uDF82", \
@":custard:" : @"\\uD83C\\uDF6E", \
@":pudding:" : @"\\uD83C\\uDF6E", \
@":flan:" : @"\\uD83C\\uDF6E", \
@":lollipop:" : @"\\uD83C\\uDF6D", \
@":candy:" : @"\\uD83C\\uDF6C", \
@":chocolate_bar:" : @"\\uD83C\\uDF6B", \
@":popcorn:" : @"\\uD83C\\uDF7F", \
@":doughnut:" : @"\\uD83C\\uDF69", \
@":cookie:" : @"\\uD83C\\uDF6A", \
@":chestnut:" : @"\\uD83C\\uDF30", \
@":peanuts:" : @"\\uD83E\\uDD5C", \
@":shelled_peanut:" : @"\\uD83E\\uDD5C", \
@":beans:" : @"\\uD83E\\uDED8", \
@":honey_pot:" : @"\\uD83C\\uDF6F", \
@":milk:" : @"\\uD83E\\uDD5B", \
@":glass_of_milk:" : @"\\uD83E\\uDD5B", \
@":pouring_liquid:" : @"\\uD83E\\uDED7", \
@":baby_bottle:" : @"\\uD83C\\uDF7C", \
@":teapot:" : @"\\uD83E\\uDED6", \
@":coffee:" : @"☕", \
@":tea:" : @"\\uD83C\\uDF75", \
@":mate:" : @"\\uD83E\\uDDC9", \
@":beverage_box:" : @"\\uD83E\\uDDC3", \
@":cup_with_straw:" : @"\\uD83E\\uDD64", \
@":bubble_tea:" : @"\\uD83E\\uDDCB", \
@":sake:" : @"\\uD83C\\uDF76", \
@":beer:" : @"\\uD83C\\uDF7A", \
@":beers:" : @"\\uD83C\\uDF7B", \
@":champagne_glass:" : @"\\uD83E\\uDD42", \
@":clinking_glass:" : @"\\uD83E\\uDD42", \
@":wine_glass:" : @"\\uD83C\\uDF77", \
@":tumbler_glass:" : @"\\uD83E\\uDD43", \
@":whisky:" : @"\\uD83E\\uDD43", \
@":cocktail:" : @"\\uD83C\\uDF78", \
@":tropical_drink:" : @"\\uD83C\\uDF79", \
@":champagne:" : @"\\uD83C\\uDF7E", \
@":bottle_with_popping_cork:" : @"\\uD83C\\uDF7E", \
@":ice_cube:" : @"\\uD83E\\uDDCA", \
@":spoon:" : @"\\uD83E\\uDD44", \
@":fork_and_knife:" : @"\\uD83C\\uDF74", \
@":fork_knife_plate:" : @"\\uD83C\\uDF7D️", \
@":fork_and_knife_with_plate:" : @"\\uD83C\\uDF7D️", \
@":bowl_with_spoon:" : @"\\uD83E\\uDD63", \
@":takeout_box:" : @"\\uD83E\\uDD61", \
@":chopsticks:" : @"\\uD83E\\uDD62", \
@":salt:" : @"\\uD83E\\uDDC2", \
@":soccer:" : @"⚽", \
@":basketball:" : @"\\uD83C\\uDFC0", \
@":football:" : @"\\uD83C\\uDFC8", \
@":baseball:" : @"⚾", \
@":softball:" : @"\\uD83E\\uDD4E", \
@":tennis:" : @"\\uD83C\\uDFBE", \
@":volleyball:" : @"\\uD83C\\uDFD0", \
@":rugby_football:" : @"\\uD83C\\uDFC9", \
@":flying_disc:" : @"\\uD83E\\uDD4F", \
@":8ball:" : @"\\uD83C\\uDFB1", \
@":yo_yo:" : @"\\uD83E\\uDE80", \
@":ping_pong:" : @"\\uD83C\\uDFD3", \
@":table_tennis:" : @"\\uD83C\\uDFD3", \
@":badminton:" : @"\\uD83C\\uDFF8", \
@":hockey:" : @"\\uD83C\\uDFD2", \
@":field_hockey:" : @"\\uD83C\\uDFD1", \
@":lacrosse:" : @"\\uD83E\\uDD4D", \
@":cricket_game:" : @"\\uD83C\\uDFCF", \
@":cricket_bat_ball:" : @"\\uD83C\\uDFCF", \
@":boomerang:" : @"\\uD83E\\uDE83", \
@":goal:" : @"\\uD83E\\uDD45", \
@":goal_net:" : @"\\uD83E\\uDD45", \
@":golf:" : @"⛳", \
@":kite:" : @"\\uD83E\\uDE81", \
@":playground_slide:" : @"\\uD83D\\uDEDD", \
@":bow_and_arrow:" : @"\\uD83C\\uDFF9", \
@":archery:" : @"\\uD83C\\uDFF9", \
@":fishing_pole_and_fish:" : @"\\uD83C\\uDFA3", \
@":diving_mask:" : @"\\uD83E\\uDD3F", \
@":boxing_glove:" : @"\\uD83E\\uDD4A", \
@":boxing_gloves:" : @"\\uD83E\\uDD4A", \
@":martial_arts_uniform:" : @"\\uD83E\\uDD4B", \
@":karate_uniform:" : @"\\uD83E\\uDD4B", \
@":running_shirt_with_sash:" : @"\\uD83C\\uDFBD", \
@":skateboard:" : @"\\uD83D\\uDEF9", \
@":roller_skate:" : @"\\uD83D\\uDEFC", \
@":sled:" : @"\\uD83D\\uDEF7", \
@":ice_skate:" : @"⛸️", \
@":curling_stone:" : @"\\uD83E\\uDD4C", \
@":ski:" : @"\\uD83C\\uDFBF", \
@":skier:" : @"⛷️", \
@":snowboarder:" : @"\\uD83C\\uDFC2", \
@":parachute:" : @"\\uD83E\\uDE82", \
@":person_lifting_weights:" : @"\\uD83C\\uDFCB️", \
@":lifter:" : @"\\uD83C\\uDFCB️", \
@":weight_lifter:" : @"\\uD83C\\uDFCB️", \
@":woman_lifting_weights:" : @"\\uD83C\\uDFCB️‍♀️", \
@":man_lifting_weights:" : @"\\uD83C\\uDFCB️‍♂️", \
@":people_wrestling:" : @"\\uD83E\\uDD3C", \
@":wrestlers:" : @"\\uD83E\\uDD3C", \
@":wrestling:" : @"\\uD83E\\uDD3C", \
@":women_wrestling:" : @"\\uD83E\\uDD3C‍♀️", \
@":men_wrestling:" : @"\\uD83E\\uDD3C‍♂️", \
@":person_doing_cartwheel:" : @"\\uD83E\\uDD38", \
@":cartwheel:" : @"\\uD83E\\uDD38", \
@":woman_cartwheeling:" : @"\\uD83E\\uDD38‍♀️", \
@":man_cartwheeling:" : @"\\uD83E\\uDD38‍♂️", \
@":person_bouncing_ball:" : @"⛹️", \
@":basketball_player:" : @"⛹️", \
@":person_with_ball:" : @"⛹️", \
@":woman_bouncing_ball:" : @"⛹️‍♀️", \
@":man_bouncing_ball:" : @"⛹️‍♂️", \
@":person_fencing:" : @"\\uD83E\\uDD3A", \
@":fencer:" : @"\\uD83E\\uDD3A", \
@":fencing:" : @"\\uD83E\\uDD3A", \
@":person_playing_handball:" : @"\\uD83E\\uDD3E", \
@":handball:" : @"\\uD83E\\uDD3E", \
@":woman_playing_handball:" : @"\\uD83E\\uDD3E‍♀️", \
@":man_playing_handball:" : @"\\uD83E\\uDD3E‍♂️", \
@":person_golfing:" : @"\\uD83C\\uDFCC️", \
@":golfer:" : @"\\uD83C\\uDFCC️", \
@":woman_golfing:" : @"\\uD83C\\uDFCC️‍♀️", \
@":man_golfing:" : @"\\uD83C\\uDFCC️‍♂️", \
@":horse_racing:" : @"\\uD83C\\uDFC7", \
@":person_in_lotus_position:" : @"\\uD83E\\uDDD8", \
@":woman_in_lotus_position:" : @"\\uD83E\\uDDD8‍♀️", \
@":man_in_lotus_position:" : @"\\uD83E\\uDDD8‍♂️", \
@":person_surfing:" : @"\\uD83C\\uDFC4", \
@":surfer:" : @"\\uD83C\\uDFC4", \
@":woman_surfing:" : @"\\uD83C\\uDFC4‍♀️", \
@":man_surfing:" : @"\\uD83C\\uDFC4‍♂️", \
@":person_swimming:" : @"\\uD83C\\uDFCA", \
@":swimmer:" : @"\\uD83C\\uDFCA", \
@":woman_swimming:" : @"\\uD83C\\uDFCA‍♀️", \
@":man_swimming:" : @"\\uD83C\\uDFCA‍♂️", \
@":person_playing_water_polo:" : @"\\uD83E\\uDD3D", \
@":water_polo:" : @"\\uD83E\\uDD3D", \
@":woman_playing_water_polo:" : @"\\uD83E\\uDD3D‍♀️", \
@":man_playing_water_polo:" : @"\\uD83E\\uDD3D‍♂️", \
@":person_rowing_boat:" : @"\\uD83D\\uDEA3", \
@":rowboat:" : @"\\uD83D\\uDEA3", \
@":woman_rowing_boat:" : @"\\uD83D\\uDEA3‍♀️", \
@":man_rowing_boat:" : @"\\uD83D\\uDEA3‍♂️", \
@":person_climbing:" : @"\\uD83E\\uDDD7", \
@":woman_climbing:" : @"\\uD83E\\uDDD7‍♀️", \
@":man_climbing:" : @"\\uD83E\\uDDD7‍♂️", \
@":person_mountain_biking:" : @"\\uD83D\\uDEB5", \
@":mountain_bicyclist:" : @"\\uD83D\\uDEB5", \
@":woman_mountain_biking:" : @"\\uD83D\\uDEB5‍♀️", \
@":man_mountain_biking:" : @"\\uD83D\\uDEB5‍♂️", \
@":person_biking:" : @"\\uD83D\\uDEB4", \
@":bicyclist:" : @"\\uD83D\\uDEB4", \
@":woman_biking:" : @"\\uD83D\\uDEB4‍♀️", \
@":man_biking:" : @"\\uD83D\\uDEB4‍♂️", \
@":trophy:" : @"\\uD83C\\uDFC6", \
@":first_place:" : @"\\uD83E\\uDD47", \
@":first_place_medal:" : @"\\uD83E\\uDD47", \
@":second_place:" : @"\\uD83E\\uDD48", \
@":second_place_medal:" : @"\\uD83E\\uDD48", \
@":third_place:" : @"\\uD83E\\uDD49", \
@":third_place_medal:" : @"\\uD83E\\uDD49", \
@":medal:" : @"\\uD83C\\uDFC5", \
@":sports_medal:" : @"\\uD83C\\uDFC5", \
@":military_medal:" : @"\\uD83C\\uDF96️", \
@":rosette:" : @"\\uD83C\\uDFF5️", \
@":reminder_ribbon:" : @"\\uD83C\\uDF97️", \
@":ticket:" : @"\\uD83C\\uDFAB", \
@":tickets:" : @"\\uD83C\\uDF9F️", \
@":admission_tickets:" : @"\\uD83C\\uDF9F️", \
@":circus_tent:" : @"\\uD83C\\uDFAA", \
@":person_juggling:" : @"\\uD83E\\uDD39", \
@":juggling:" : @"\\uD83E\\uDD39", \
@":juggler:" : @"\\uD83E\\uDD39", \
@":woman_juggling:" : @"\\uD83E\\uDD39‍♀️", \
@":man_juggling:" : @"\\uD83E\\uDD39‍♂️", \
@":performing_arts:" : @"\\uD83C\\uDFAD", \
@":ballet_shoes:" : @"\\uD83E\\uDE70", \
@":art:" : @"\\uD83C\\uDFA8", \
@":clapper:" : @"\\uD83C\\uDFAC", \
@":microphone:" : @"\\uD83C\\uDFA4", \
@":headphones:" : @"\\uD83C\\uDFA7", \
@":musical_score:" : @"\\uD83C\\uDFBC", \
@":musical_keyboard:" : @"\\uD83C\\uDFB9", \
@":drum:" : @"\\uD83E\\uDD41", \
@":drum_with_drumsticks:" : @"\\uD83E\\uDD41", \
@":long_drum:" : @"\\uD83E\\uDE98", \
@":saxophone:" : @"\\uD83C\\uDFB7", \
@":trumpet:" : @"\\uD83C\\uDFBA", \
@":accordion:" : @"\\uD83E\\uDE97", \
@":guitar:" : @"\\uD83C\\uDFB8", \
@":banjo:" : @"\\uD83E\\uDE95", \
@":violin:" : @"\\uD83C\\uDFBB", \
@":game_die:" : @"\\uD83C\\uDFB2", \
@":chess_pawn:" : @"♟️", \
@":dart:" : @"\\uD83C\\uDFAF", \
@":bowling:" : @"\\uD83C\\uDFB3", \
@":video_game:" : @"\\uD83C\\uDFAE", \
@":slot_machine:" : @"\\uD83C\\uDFB0", \
@":jigsaw:" : @"\\uD83E\\uDDE9", \
@":red_car:" : @"\\uD83D\\uDE97", \
@":taxi:" : @"\\uD83D\\uDE95", \
@":blue_car:" : @"\\uD83D\\uDE99", \
@":pickup_truck:" : @"\\uD83D\\uDEFB", \
@":bus:" : @"\\uD83D\\uDE8C", \
@":trolleybus:" : @"\\uD83D\\uDE8E", \
@":race_car:" : @"\\uD83C\\uDFCE️", \
@":racing_car:" : @"\\uD83C\\uDFCE️", \
@":police_car:" : @"\\uD83D\\uDE93", \
@":ambulance:" : @"\\uD83D\\uDE91", \
@":fire_engine:" : @"\\uD83D\\uDE92", \
@":minibus:" : @"\\uD83D\\uDE90", \
@":truck:" : @"\\uD83D\\uDE9A", \
@":articulated_lorry:" : @"\\uD83D\\uDE9B", \
@":tractor:" : @"\\uD83D\\uDE9C", \
@":probing_cane:" : @"\\uD83E\\uDDAF", \
@":crutch:" : @"\\uD83E\\uDE7C", \
@":manual_wheelchair:" : @"\\uD83E\\uDDBD", \
@":motorized_wheelchair:" : @"\\uD83E\\uDDBC", \
@":scooter:" : @"\\uD83D\\uDEF4", \
@":bike:" : @"\\uD83D\\uDEB2", \
@":motor_scooter:" : @"\\uD83D\\uDEF5", \
@":motorbike:" : @"\\uD83D\\uDEF5", \
@":motorcycle:" : @"\\uD83C\\uDFCD️", \
@":racing_motorcycle:" : @"\\uD83C\\uDFCD️", \
@":auto_rickshaw:" : @"\\uD83D\\uDEFA", \
@":wheel:" : @"\\uD83D\\uDEDE", \
@":rotating_light:" : @"\\uD83D\\uDEA8", \
@":oncoming_police_car:" : @"\\uD83D\\uDE94", \
@":oncoming_bus:" : @"\\uD83D\\uDE8D", \
@":oncoming_automobile:" : @"\\uD83D\\uDE98", \
@":oncoming_taxi:" : @"\\uD83D\\uDE96", \
@":aerial_tramway:" : @"\\uD83D\\uDEA1", \
@":mountain_cableway:" : @"\\uD83D\\uDEA0", \
@":suspension_railway:" : @"\\uD83D\\uDE9F", \
@":railway_car:" : @"\\uD83D\\uDE83", \
@":train:" : @"\\uD83D\\uDE8B", \
@":mountain_railway:" : @"\\uD83D\\uDE9E", \
@":monorail:" : @"\\uD83D\\uDE9D", \
@":bullettrain_side:" : @"\\uD83D\\uDE84", \
@":bullettrain_front:" : @"\\uD83D\\uDE85", \
@":light_rail:" : @"\\uD83D\\uDE88", \
@":steam_locomotive:" : @"\\uD83D\\uDE82", \
@":train2:" : @"\\uD83D\\uDE86", \
@":metro:" : @"\\uD83D\\uDE87", \
@":tram:" : @"\\uD83D\\uDE8A", \
@":station:" : @"\\uD83D\\uDE89", \
@":airplane:" : @"✈️", \
@":airplane_departure:" : @"\\uD83D\\uDEEB", \
@":airplane_arriving:" : @"\\uD83D\\uDEEC", \
@":airplane_small:" : @"\\uD83D\\uDEE9️", \
@":small_airplane:" : @"\\uD83D\\uDEE9️", \
@":seat:" : @"\\uD83D\\uDCBA", \
@":satellite_orbital:" : @"\\uD83D\\uDEF0️", \
@":rocket:" : @"\\uD83D\\uDE80", \
@":flying_saucer:" : @"\\uD83D\\uDEF8", \
@":helicopter:" : @"\\uD83D\\uDE81", \
@":canoe:" : @"\\uD83D\\uDEF6", \
@":kayak:" : @"\\uD83D\\uDEF6", \
@":sailboat:" : @"⛵", \
@":speedboat:" : @"\\uD83D\\uDEA4", \
@":motorboat:" : @"\\uD83D\\uDEE5️", \
@":cruise_ship:" : @"\\uD83D\\uDEF3️", \
@":passenger_ship:" : @"\\uD83D\\uDEF3️", \
@":ferry:" : @"⛴️", \
@":ship:" : @"\\uD83D\\uDEA2", \
@":ring_buoy:" : @"\\uD83D\\uDEDF", \
@":anchor:" : @"⚓", \
@":hook:" : @"\\uD83E\\uDE9D", \
@":fuelpump:" : @"⛽", \
@":construction:" : @"\\uD83D\\uDEA7", \
@":vertical_traffic_light:" : @"\\uD83D\\uDEA6", \
@":traffic_light:" : @"\\uD83D\\uDEA5", \
@":busstop:" : @"\\uD83D\\uDE8F", \
@":map:" : @"\\uD83D\\uDDFA️", \
@":world_map:" : @"\\uD83D\\uDDFA️", \
@":moyai:" : @"\\uD83D\\uDDFF", \
@":statue_of_liberty:" : @"\\uD83D\\uDDFD", \
@":tokyo_tower:" : @"\\uD83D\\uDDFC", \
@":european_castle:" : @"\\uD83C\\uDFF0", \
@":japanese_castle:" : @"\\uD83C\\uDFEF", \
@":stadium:" : @"\\uD83C\\uDFDF️", \
@":ferris_wheel:" : @"\\uD83C\\uDFA1", \
@":roller_coaster:" : @"\\uD83C\\uDFA2", \
@":carousel_horse:" : @"\\uD83C\\uDFA0", \
@":fountain:" : @"⛲", \
@":beach_umbrella:" : @"⛱️", \
@":umbrella_on_ground:" : @"⛱️", \
@":beach:" : @"\\uD83C\\uDFD6️", \
@":beach_with_umbrella:" : @"\\uD83C\\uDFD6️", \
@":island:" : @"\\uD83C\\uDFDD️", \
@":desert_island:" : @"\\uD83C\\uDFDD️", \
@":desert:" : @"\\uD83C\\uDFDC️", \
@":volcano:" : @"\\uD83C\\uDF0B", \
@":mountain:" : @"⛰️", \
@":mountain_snow:" : @"\\uD83C\\uDFD4️", \
@":snow_capped_mountain:" : @"\\uD83C\\uDFD4️", \
@":mount_fuji:" : @"\\uD83D\\uDDFB", \
@":camping:" : @"\\uD83C\\uDFD5️", \
@":tent:" : @"⛺", \
@":house:" : @"\\uD83C\\uDFE0", \
@":house_with_garden:" : @"\\uD83C\\uDFE1", \
@":homes:" : @"\\uD83C\\uDFD8️", \
@":house_buildings:" : @"\\uD83C\\uDFD8️", \
@":house_abandoned:" : @"\\uD83C\\uDFDA️", \
@":derelict_house_building:" : @"\\uD83C\\uDFDA️", \
@":hut:" : @"\\uD83D\\uDED6", \
@":construction_site:" : @"\\uD83C\\uDFD7️", \
@":building_construction:" : @"\\uD83C\\uDFD7️", \
@":factory:" : @"\\uD83C\\uDFED", \
@":office:" : @"\\uD83C\\uDFE2", \
@":department_store:" : @"\\uD83C\\uDFEC", \
@":post_office:" : @"\\uD83C\\uDFE3", \
@":european_post_office:" : @"\\uD83C\\uDFE4", \
@":hospital:" : @"\\uD83C\\uDFE5", \
@":bank:" : @"\\uD83C\\uDFE6", \
@":hotel:" : @"\\uD83C\\uDFE8", \
@":convenience_store:" : @"\\uD83C\\uDFEA", \
@":school:" : @"\\uD83C\\uDFEB", \
@":love_hotel:" : @"\\uD83C\\uDFE9", \
@":wedding:" : @"\\uD83D\\uDC92", \
@":classical_building:" : @"\\uD83C\\uDFDB️", \
@":church:" : @"⛪", \
@":mosque:" : @"\\uD83D\\uDD4C", \
@":synagogue:" : @"\\uD83D\\uDD4D", \
@":hindu_temple:" : @"\\uD83D\\uDED5", \
@":kaaba:" : @"\\uD83D\\uDD4B", \
@":shinto_shrine:" : @"⛩️", \
@":railway_track:" : @"\\uD83D\\uDEE4️", \
@":railroad_track:" : @"\\uD83D\\uDEE4️", \
@":motorway:" : @"\\uD83D\\uDEE3️", \
@":japan:" : @"\\uD83D\\uDDFE", \
@":rice_scene:" : @"\\uD83C\\uDF91", \
@":park:" : @"\\uD83C\\uDFDE️", \
@":national_park:" : @"\\uD83C\\uDFDE️", \
@":sunrise:" : @"\\uD83C\\uDF05", \
@":sunrise_over_mountains:" : @"\\uD83C\\uDF04", \
@":stars:" : @"\\uD83C\\uDF20", \
@":sparkler:" : @"\\uD83C\\uDF87", \
@":fireworks:" : @"\\uD83C\\uDF86", \
@":city_sunset:" : @"\\uD83C\\uDF07", \
@":city_sunrise:" : @"\\uD83C\\uDF07", \
@":city_dusk:" : @"\\uD83C\\uDF06", \
@":cityscape:" : @"\\uD83C\\uDFD9️", \
@":night_with_stars:" : @"\\uD83C\\uDF03", \
@":milky_way:" : @"\\uD83C\\uDF0C", \
@":bridge_at_night:" : @"\\uD83C\\uDF09", \
@":foggy:" : @"\\uD83C\\uDF01", \
@":watch:" : @"⌚", \
@":mobile_phone:" : @"\\uD83D\\uDCF1", \
@":iphone:" : @"\\uD83D\\uDCF1", \
@":calling:" : @"\\uD83D\\uDCF2", \
@":computer:" : @"\\uD83D\\uDCBB", \
@":keyboard:" : @"⌨️", \
@":desktop:" : @"\\uD83D\\uDDA5️", \
@":desktop_computer:" : @"\\uD83D\\uDDA5️", \
@":printer:" : @"\\uD83D\\uDDA8️", \
@":mouse_three_button:" : @"\\uD83D\\uDDB1️", \
@":three_button_mouse:" : @"\\uD83D\\uDDB1️", \
@":trackball:" : @"\\uD83D\\uDDB2️", \
@":joystick:" : @"\\uD83D\\uDD79️", \
@":compression:" : @"\\uD83D\\uDDDC️", \
@":minidisc:" : @"\\uD83D\\uDCBD", \
@":floppy_disk:" : @"\\uD83D\\uDCBE", \
@":cd:" : @"\\uD83D\\uDCBF", \
@":dvd:" : @"\\uD83D\\uDCC0", \
@":vhs:" : @"\\uD83D\\uDCFC", \
@":camera:" : @"\\uD83D\\uDCF7", \
@":camera_with_flash:" : @"\\uD83D\\uDCF8", \
@":video_camera:" : @"\\uD83D\\uDCF9", \
@":movie_camera:" : @"\\uD83C\\uDFA5", \
@":projector:" : @"\\uD83D\\uDCFD️", \
@":film_projector:" : @"\\uD83D\\uDCFD️", \
@":film_frames:" : @"\\uD83C\\uDF9E️", \
@":telephone_receiver:" : @"\\uD83D\\uDCDE", \
@":telephone:" : @"☎️", \
@":pager:" : @"\\uD83D\\uDCDF", \
@":fax:" : @"\\uD83D\\uDCE0", \
@":tv:" : @"\\uD83D\\uDCFA", \
@":radio:" : @"\\uD83D\\uDCFB", \
@":microphone2:" : @"\\uD83C\\uDF99️", \
@":studio_microphone:" : @"\\uD83C\\uDF99️", \
@":level_slider:" : @"\\uD83C\\uDF9A️", \
@":control_knobs:" : @"\\uD83C\\uDF9B️", \
@":compass:" : @"\\uD83E\\uDDED", \
@":stopwatch:" : @"⏱️", \
@":timer:" : @"⏲️", \
@":timer_clock:" : @"⏲️", \
@":alarm_clock:" : @"⏰", \
@":clock:" : @"\\uD83D\\uDD70️", \
@":mantlepiece_clock:" : @"\\uD83D\\uDD70️", \
@":hourglass:" : @"⌛", \
@":hourglass_flowing_sand:" : @"⏳", \
@":satellite:" : @"\\uD83D\\uDCE1", \
@":battery:" : @"\\uD83D\\uDD0B", \
@":low_battery:" : @"\\uD83E\\uDEAB", \
@":electric_plug:" : @"\\uD83D\\uDD0C", \
@":bulb:" : @"\\uD83D\\uDCA1", \
@":flashlight:" : @"\\uD83D\\uDD26", \
@":candle:" : @"\\uD83D\\uDD6F️", \
@":diya_lamp:" : @"\\uD83E\\uDE94", \
@":fire_extinguisher:" : @"\\uD83E\\uDDEF", \
@":oil:" : @"\\uD83D\\uDEE2️", \
@":oil_drum:" : @"\\uD83D\\uDEE2️", \
@":money_with_wings:" : @"\\uD83D\\uDCB8", \
@":dollar:" : @"\\uD83D\\uDCB5", \
@":yen:" : @"\\uD83D\\uDCB4", \
@":euro:" : @"\\uD83D\\uDCB6", \
@":pound:" : @"\\uD83D\\uDCB7", \
@":coin:" : @"\\uD83E\\uDE99", \
@":moneybag:" : @"\\uD83D\\uDCB0", \
@":credit_card:" : @"\\uD83D\\uDCB3", \
@":identification_card:" : @"\\uD83E\\uDEAA", \
@":gem:" : @"\\uD83D\\uDC8E", \
@":scales:" : @"⚖️", \
@":ladder:" : @"\\uD83E\\uDE9C", \
@":toolbox:" : @"\\uD83E\\uDDF0", \
@":screwdriver:" : @"\\uD83E\\uDE9B", \
@":wrench:" : @"\\uD83D\\uDD27", \
@":hammer:" : @"\\uD83D\\uDD28", \
@":hammer_pick:" : @"⚒️", \
@":hammer_and_pick:" : @"⚒️", \
@":tools:" : @"\\uD83D\\uDEE0️", \
@":hammer_and_wrench:" : @"\\uD83D\\uDEE0️", \
@":pick:" : @"⛏️", \
@":carpentry_saw:" : @"\\uD83E\\uDE9A", \
@":nut_and_bolt:" : @"\\uD83D\\uDD29", \
@":gear:" : @"⚙️", \
@":mouse_trap:" : @"\\uD83E\\uDEA4", \
@":bricks:" : @"\\uD83E\\uDDF1", \
@":chains:" : @"⛓️", \
@":magnet:" : @"\\uD83E\\uDDF2", \
@":gun:" : @"\\uD83D\\uDD2B", \
@":bomb:" : @"\\uD83D\\uDCA3", \
@":firecracker:" : @"\\uD83E\\uDDE8", \
@":axe:" : @"\\uD83E\\uDE93", \
@":knife:" : @"\\uD83D\\uDD2A", \
@":dagger:" : @"\\uD83D\\uDDE1️", \
@":dagger_knife:" : @"\\uD83D\\uDDE1️", \
@":crossed_swords:" : @"⚔️", \
@":shield:" : @"\\uD83D\\uDEE1️", \
@":smoking:" : @"\\uD83D\\uDEAC", \
@":coffin:" : @"⚰️", \
@":headstone:" : @"\\uD83E\\uDEA6", \
@":urn:" : @"⚱️", \
@":funeral_urn:" : @"⚱️", \
@":amphora:" : @"\\uD83C\\uDFFA", \
@":crystal_ball:" : @"\\uD83D\\uDD2E", \
@":prayer_beads:" : @"\\uD83D\\uDCFF", \
@":nazar_amulet:" : @"\\uD83E\\uDDFF", \
@":hamsa:" : @"\\uD83E\\uDEAC", \
@":barber:" : @"\\uD83D\\uDC88", \
@":alembic:" : @"⚗️", \
@":telescope:" : @"\\uD83D\\uDD2D", \
@":microscope:" : @"\\uD83D\\uDD2C", \
@":hole:" : @"\\uD83D\\uDD73️", \
@":x_ray:" : @"\\uD83E\\uDE7B", \
@":adhesive_bandage:" : @"\\uD83E\\uDE79", \
@":stethoscope:" : @"\\uD83E\\uDE7A", \
@":pill:" : @"\\uD83D\\uDC8A", \
@":syringe:" : @"\\uD83D\\uDC89", \
@":drop_of_blood:" : @"\\uD83E\\uDE78", \
@":dna:" : @"\\uD83E\\uDDEC", \
@":microbe:" : @"\\uD83E\\uDDA0", \
@":petri_dish:" : @"\\uD83E\\uDDEB", \
@":test_tube:" : @"\\uD83E\\uDDEA", \
@":thermometer:" : @"\\uD83C\\uDF21️", \
@":broom:" : @"\\uD83E\\uDDF9", \
@":plunger:" : @"\\uD83E\\uDEA0", \
@":basket:" : @"\\uD83E\\uDDFA", \
@":roll_of_paper:" : @"\\uD83E\\uDDFB", \
@":toilet:" : @"\\uD83D\\uDEBD", \
@":potable_water:" : @"\\uD83D\\uDEB0", \
@":shower:" : @"\\uD83D\\uDEBF", \
@":bathtub:" : @"\\uD83D\\uDEC1", \
@":bath:" : @"\\uD83D\\uDEC0", \
@":soap:" : @"\\uD83E\\uDDFC", \
@":toothbrush:" : @"\\uD83E\\uDEA5", \
@":razor:" : @"\\uD83E\\uDE92", \
@":sponge:" : @"\\uD83E\\uDDFD", \
@":bucket:" : @"\\uD83E\\uDEA3", \
@":squeeze_bottle:" : @"\\uD83E\\uDDF4", \
@":bellhop:" : @"\\uD83D\\uDECE️", \
@":bellhop_bell:" : @"\\uD83D\\uDECE️", \
@":key:" : @"\\uD83D\\uDD11", \
@":key2:" : @"\\uD83D\\uDDDD️", \
@":old_key:" : @"\\uD83D\\uDDDD️", \
@":door:" : @"\\uD83D\\uDEAA", \
@":chair:" : @"\\uD83E\\uDE91", \
@":couch:" : @"\\uD83D\\uDECB️", \
@":couch_and_lamp:" : @"\\uD83D\\uDECB️", \
@":bed:" : @"\\uD83D\\uDECF️", \
@":sleeping_accommodation:" : @"\\uD83D\\uDECC", \
@":teddy_bear:" : @"\\uD83E\\uDDF8", \
@":nesting_dolls:" : @"\\uD83E\\uDE86", \
@":frame_photo:" : @"\\uD83D\\uDDBC️", \
@":frame_with_picture:" : @"\\uD83D\\uDDBC️", \
@":mirror:" : @"\\uD83E\\uDE9E", \
@":window:" : @"\\uD83E\\uDE9F", \
@":shopping_bags:" : @"\\uD83D\\uDECD️", \
@":shopping_cart:" : @"\\uD83D\\uDED2", \
@":shopping_trolley:" : @"\\uD83D\\uDED2", \
@":gift:" : @"\\uD83C\\uDF81", \
@":balloon:" : @"\\uD83C\\uDF88", \
@":flags:" : @"\\uD83C\\uDF8F", \
@":ribbon:" : @"\\uD83C\\uDF80", \
@":magic_wand:" : @"\\uD83E\\uDE84", \
@":pi\\xf1ata:" : @"\\uD83E\\uDE85", \
@":confetti_ball:" : @"\\uD83C\\uDF8A", \
@":tada:" : @"\\uD83C\\uDF89", \
@":dolls:" : @"\\uD83C\\uDF8E", \
@":izakaya_lantern:" : @"\\uD83C\\uDFEE", \
@":wind_chime:" : @"\\uD83C\\uDF90", \
@":mirror_ball:" : @"\\uD83E\\uDEA9", \
@":red_envelope:" : @"\\uD83E\\uDDE7", \
@":envelope:" : @"✉️", \
@":envelope_with_arrow:" : @"\\uD83D\\uDCE9", \
@":incoming_envelope:" : @"\\uD83D\\uDCE8", \
@":e_mail:" : @"\\uD83D\\uDCE7", \
@":email:" : @"\\uD83D\\uDCE7", \
@":love_letter:" : @"\\uD83D\\uDC8C", \
@":inbox_tray:" : @"\\uD83D\\uDCE5", \
@":outbox_tray:" : @"\\uD83D\\uDCE4", \
@":package:" : @"\\uD83D\\uDCE6", \
@":label:" : @"\\uD83C\\uDFF7️", \
@":placard:" : @"\\uD83E\\uDEA7", \
@":mailbox_closed:" : @"\\uD83D\\uDCEA", \
@":mailbox:" : @"\\uD83D\\uDCEB", \
@":mailbox_with_mail:" : @"\\uD83D\\uDCEC", \
@":mailbox_with_no_mail:" : @"\\uD83D\\uDCED", \
@":postbox:" : @"\\uD83D\\uDCEE", \
@":postal_horn:" : @"\\uD83D\\uDCEF", \
@":scroll:" : @"\\uD83D\\uDCDC", \
@":page_with_curl:" : @"\\uD83D\\uDCC3", \
@":page_facing_up:" : @"\\uD83D\\uDCC4", \
@":bookmark_tabs:" : @"\\uD83D\\uDCD1", \
@":receipt:" : @"\\uD83E\\uDDFE", \
@":bar_chart:" : @"\\uD83D\\uDCCA", \
@":chart_with_upwards_trend:" : @"\\uD83D\\uDCC8", \
@":chart_with_downwards_trend:" : @"\\uD83D\\uDCC9", \
@":notepad_spiral:" : @"\\uD83D\\uDDD2️", \
@":spiral_note_pad:" : @"\\uD83D\\uDDD2️", \
@":calendar_spiral:" : @"\\uD83D\\uDDD3️", \
@":spiral_calendar_pad:" : @"\\uD83D\\uDDD3️", \
@":calendar:" : @"\\uD83D\\uDCC6", \
@":date:" : @"\\uD83D\\uDCC5", \
@":wastebasket:" : @"\\uD83D\\uDDD1️", \
@":card_index:" : @"\\uD83D\\uDCC7", \
@":card_box:" : @"\\uD83D\\uDDC3️", \
@":card_file_box:" : @"\\uD83D\\uDDC3️", \
@":ballot_box:" : @"\\uD83D\\uDDF3️", \
@":ballot_box_with_ballot:" : @"\\uD83D\\uDDF3️", \
@":file_cabinet:" : @"\\uD83D\\uDDC4️", \
@":clipboard:" : @"\\uD83D\\uDCCB", \
@":file_folder:" : @"\\uD83D\\uDCC1", \
@":open_file_folder:" : @"\\uD83D\\uDCC2", \
@":dividers:" : @"\\uD83D\\uDDC2️", \
@":card_index_dividers:" : @"\\uD83D\\uDDC2️", \
@":newspaper2:" : @"\\uD83D\\uDDDE️", \
@":rolled_up_newspaper:" : @"\\uD83D\\uDDDE️", \
@":newspaper:" : @"\\uD83D\\uDCF0", \
@":notebook:" : @"\\uD83D\\uDCD3", \
@":notebook_with_decorative_cover:" : @"\\uD83D\\uDCD4", \
@":ledger:" : @"\\uD83D\\uDCD2", \
@":closed_book:" : @"\\uD83D\\uDCD5", \
@":green_book:" : @"\\uD83D\\uDCD7", \
@":blue_book:" : @"\\uD83D\\uDCD8", \
@":orange_book:" : @"\\uD83D\\uDCD9", \
@":books:" : @"\\uD83D\\uDCDA", \
@":book:" : @"\\uD83D\\uDCD6", \
@":bookmark:" : @"\\uD83D\\uDD16", \
@":safety_pin:" : @"\\uD83E\\uDDF7", \
@":link:" : @"\\uD83D\\uDD17", \
@":paperclip:" : @"\\uD83D\\uDCCE", \
@":paperclips:" : @"\\uD83D\\uDD87️", \
@":linked_paperclips:" : @"\\uD83D\\uDD87️", \
@":triangular_ruler:" : @"\\uD83D\\uDCD0", \
@":straight_ruler:" : @"\\uD83D\\uDCCF", \
@":abacus:" : @"\\uD83E\\uDDEE", \
@":pushpin:" : @"\\uD83D\\uDCCC", \
@":round_pushpin:" : @"\\uD83D\\uDCCD", \
@":scissors:" : @"✂️", \
@":pen_ballpoint:" : @"\\uD83D\\uDD8A️", \
@":lower_left_ballpoint_pen:" : @"\\uD83D\\uDD8A️", \
@":pen_fountain:" : @"\\uD83D\\uDD8B️", \
@":lower_left_fountain_pen:" : @"\\uD83D\\uDD8B️", \
@":black_nib:" : @"✒️", \
@":paintbrush:" : @"\\uD83D\\uDD8C️", \
@":lower_left_paintbrush:" : @"\\uD83D\\uDD8C️", \
@":crayon:" : @"\\uD83D\\uDD8D️", \
@":lower_left_crayon:" : @"\\uD83D\\uDD8D️", \
@":pencil:" : @"\\uD83D\\uDCDD", \
@":memo:" : @"\\uD83D\\uDCDD", \
@":pencil2:" : @"✏️", \
@":mag:" : @"\\uD83D\\uDD0D", \
@":mag_right:" : @"\\uD83D\\uDD0E", \
@":lock_with_ink_pen:" : @"\\uD83D\\uDD0F", \
@":closed_lock_with_key:" : @"\\uD83D\\uDD10", \
@":lock:" : @"\\uD83D\\uDD12", \
@":unlock:" : @"\\uD83D\\uDD13", \
@":heart:" : @"❤️", \
@":orange_heart:" : @"\\uD83E\\uDDE1", \
@":yellow_heart:" : @"\\uD83D\\uDC9B", \
@":green_heart:" : @"\\uD83D\\uDC9A", \
@":blue_heart:" : @"\\uD83D\\uDC99", \
@":purple_heart:" : @"\\uD83D\\uDC9C", \
@":black_heart:" : @"\\uD83D\\uDDA4", \
@":brown_heart:" : @"\\uD83E\\uDD0E", \
@":white_heart:" : @"\\uD83E\\uDD0D", \
@":broken_heart:" : @"\\uD83D\\uDC94", \
@":heart_exclamation:" : @"❣️", \
@":heavy_heart_exclamation_mark_ornament:" : @"❣️", \
@":two_hearts:" : @"\\uD83D\\uDC95", \
@":revolving_hearts:" : @"\\uD83D\\uDC9E", \
@":heartbeat:" : @"\\uD83D\\uDC93", \
@":heartpulse:" : @"\\uD83D\\uDC97", \
@":sparkling_heart:" : @"\\uD83D\\uDC96", \
@":cupid:" : @"\\uD83D\\uDC98", \
@":gift_heart:" : @"\\uD83D\\uDC9D", \
@":mending_heart:" : @"❤️‍\\uD83E\\uDE79", \
@":heart_on_fire:" : @"❤️‍\\uD83D\\uDD25", \
@":heart_decoration:" : @"\\uD83D\\uDC9F", \
@":peace:" : @"☮️", \
@":peace_symbol:" : @"☮️", \
@":cross:" : @"✝️", \
@":latin_cross:" : @"✝️", \
@":star_and_crescent:" : @"☪️", \
@":om_symbol:" : @"\\uD83D\\uDD49️", \
@":wheel_of_dharma:" : @"☸️", \
@":star_of_david:" : @"✡️", \
@":six_pointed_star:" : @"\\uD83D\\uDD2F", \
@":menorah:" : @"\\uD83D\\uDD4E", \
@":yin_yang:" : @"☯️", \
@":orthodox_cross:" : @"☦️", \
@":place_of_worship:" : @"\\uD83D\\uDED0", \
@":worship_symbol:" : @"\\uD83D\\uDED0", \
@":ophiuchus:" : @"⛎", \
@":aries:" : @"♈", \
@":taurus:" : @"♉", \
@":gemini:" : @"♊", \
@":cancer:" : @"♋", \
@":leo:" : @"♌", \
@":virgo:" : @"♍", \
@":libra:" : @"♎", \
@":scorpius:" : @"♏", \
@":sagittarius:" : @"♐", \
@":capricorn:" : @"♑", \
@":aquarius:" : @"♒", \
@":pisces:" : @"♓", \
@":id:" : @"\\uD83C\\uDD94", \
@":atom:" : @"⚛️", \
@":atom_symbol:" : @"⚛️", \
@":accept:" : @"\\uD83C\\uDE51", \
@":radioactive:" : @"☢️", \
@":radioactive_sign:" : @"☢️", \
@":biohazard:" : @"☣️", \
@":biohazard_sign:" : @"☣️", \
@":mobile_phone_off:" : @"\\uD83D\\uDCF4", \
@":vibration_mode:" : @"\\uD83D\\uDCF3", \
@":u6709:" : @"\\uD83C\\uDE36", \
@":u7121:" : @"\\uD83C\\uDE1A", \
@":u7533:" : @"\\uD83C\\uDE38", \
@":u55b6:" : @"\\uD83C\\uDE3A", \
@":u6708:" : @"\\uD83C\\uDE37️", \
@":eight_pointed_black_star:" : @"✴️", \
@":vs:" : @"\\uD83C\\uDD9A", \
@":white_flower:" : @"\\uD83D\\uDCAE", \
@":ideograph_advantage:" : @"\\uD83C\\uDE50", \
@":secret:" : @"㊙️", \
@":congratulations:" : @"㊗️", \
@":u5408:" : @"\\uD83C\\uDE34", \
@":u6e80:" : @"\\uD83C\\uDE35", \
@":u5272:" : @"\\uD83C\\uDE39", \
@":u7981:" : @"\\uD83C\\uDE32", \
@":a:" : @"\\uD83C\\uDD70️", \
@":b:" : @"\\uD83C\\uDD71️", \
@":ab:" : @"\\uD83C\\uDD8E", \
@":cl:" : @"\\uD83C\\uDD91", \
@":o2:" : @"\\uD83C\\uDD7E️", \
@":sos:" : @"\\uD83C\\uDD98", \
@":x:" : @"❌", \
@":o:" : @"⭕", \
@":octagonal_sign:" : @"\\uD83D\\uDED1", \
@":stop_sign:" : @"\\uD83D\\uDED1", \
@":no_entry:" : @"⛔", \
@":name_badge:" : @"\\uD83D\\uDCDB", \
@":no_entry_sign:" : @"\\uD83D\\uDEAB", \
@":100:" : @"\\uD83D\\uDCAF", \
@":anger:" : @"\\uD83D\\uDCA2", \
@":hotsprings:" : @"♨️", \
@":no_pedestrians:" : @"\\uD83D\\uDEB7", \
@":do_not_litter:" : @"\\uD83D\\uDEAF", \
@":no_bicycles:" : @"\\uD83D\\uDEB3", \
@":non_potable_water:" : @"\\uD83D\\uDEB1", \
@":underage:" : @"\\uD83D\\uDD1E", \
@":no_mobile_phones:" : @"\\uD83D\\uDCF5", \
@":no_smoking:" : @"\\uD83D\\uDEAD", \
@":exclamation:" : @"❗", \
@":grey_exclamation:" : @"❕", \
@":question:" : @"❓", \
@":grey_question:" : @"❔", \
@":bangbang:" : @"‼️", \
@":interrobang:" : @"⁉️", \
@":low_brightness:" : @"\\uD83D\\uDD05", \
@":high_brightness:" : @"\\uD83D\\uDD06", \
@":part_alternation_mark:" : @"〽️", \
@":warning:" : @"⚠️", \
@":children_crossing:" : @"\\uD83D\\uDEB8", \
@":trident:" : @"\\uD83D\\uDD31", \
@":fleur_de_lis:" : @"⚜️", \
@":beginner:" : @"\\uD83D\\uDD30", \
@":recycle:" : @"♻️", \
@":white_check_mark:" : @"✅", \
@":u6307:" : @"\\uD83C\\uDE2F", \
@":chart:" : @"\\uD83D\\uDCB9", \
@":sparkle:" : @"❇️", \
@":eight_spoked_asterisk:" : @"✳️", \
@":negative_squared_cross_mark:" : @"❎", \
@":globe_with_meridians:" : @"\\uD83C\\uDF10", \
@":diamond_shape_with_a_dot_inside:" : @"\\uD83D\\uDCA0", \
@":m:" : @"Ⓜ️", \
@":cyclone:" : @"\\uD83C\\uDF00", \
@":zzz:" : @"\\uD83D\\uDCA4", \
@":atm:" : @"\\uD83C\\uDFE7", \
@":wc:" : @"\\uD83D\\uDEBE", \
@":wheelchair:" : @"♿", \
@":parking:" : @"\\uD83C\\uDD7F️", \
@":u7a7a:" : @"\\uD83C\\uDE33", \
@":sa:" : @"\\uD83C\\uDE02️", \
@":passport_control:" : @"\\uD83D\\uDEC2", \
@":customs:" : @"\\uD83D\\uDEC3", \
@":baggage_claim:" : @"\\uD83D\\uDEC4", \
@":left_luggage:" : @"\\uD83D\\uDEC5", \
@":elevator:" : @"\\uD83D\\uDED7", \
@":mens:" : @"\\uD83D\\uDEB9", \
@":womens:" : @"\\uD83D\\uDEBA", \
@":baby_symbol:" : @"\\uD83D\\uDEBC", \
@":restroom:" : @"\\uD83D\\uDEBB", \
@":put_litter_in_its_place:" : @"\\uD83D\\uDEAE", \
@":cinema:" : @"\\uD83C\\uDFA6", \
@":signal_strength:" : @"\\uD83D\\uDCF6", \
@":koko:" : @"\\uD83C\\uDE01", \
@":symbols:" : @"\\uD83D\\uDD23", \
@":information_source:" : @"ℹ️", \
@":abc:" : @"\\uD83D\\uDD24", \
@":abcd:" : @"\\uD83D\\uDD21", \
@":capital_abcd:" : @"\\uD83D\\uDD20", \
@":ng:" : @"\\uD83C\\uDD96", \
@":ok:" : @"\\uD83C\\uDD97", \
@":up:" : @"\\uD83C\\uDD99", \
@":cool:" : @"\\uD83C\\uDD92", \
@":new:" : @"\\uD83C\\uDD95", \
@":free:" : @"\\uD83C\\uDD93", \
@":zero:" : @"0️⃣", \
@":one:" : @"1️⃣", \
@":two:" : @"2️⃣", \
@":three:" : @"3️⃣", \
@":four:" : @"4️⃣", \
@":five:" : @"5️⃣", \
@":six:" : @"6️⃣", \
@":seven:" : @"7️⃣", \
@":eight:" : @"8️⃣", \
@":nine:" : @"9️⃣", \
@":keycap_ten:" : @"\\uD83D\\uDD1F", \
@":1234:" : @"\\uD83D\\uDD22", \
@":hash:" : @"#️⃣", \
@":asterisk:" : @"*️⃣", \
@":keycap_asterisk:" : @"*️⃣", \
@":eject:" : @"⏏️", \
@":eject_symbol:" : @"⏏️", \
@":arrow_forward:" : @"▶️", \
@":pause_button:" : @"⏸️", \
@":double_vertical_bar:" : @"⏸️", \
@":play_pause:" : @"⏯️", \
@":stop_button:" : @"⏹️", \
@":record_button:" : @"⏺️", \
@":track_next:" : @"⏭️", \
@":next_track:" : @"⏭️", \
@":track_previous:" : @"⏮️", \
@":previous_track:" : @"⏮️", \
@":fast_forward:" : @"⏩", \
@":rewind:" : @"⏪", \
@":arrow_double_up:" : @"⏫", \
@":arrow_double_down:" : @"⏬", \
@":arrow_backward:" : @"◀️", \
@":arrow_up_small:" : @"\\uD83D\\uDD3C", \
@":arrow_down_small:" : @"\\uD83D\\uDD3D", \
@":arrow_right:" : @"➡️", \
@":arrow_left:" : @"⬅️", \
@":arrow_up:" : @"⬆️", \
@":arrow_down:" : @"⬇️", \
@":arrow_upper_right:" : @"↗️", \
@":arrow_lower_right:" : @"↘️", \
@":arrow_lower_left:" : @"↙️", \
@":arrow_upper_left:" : @"↖️", \
@":arrow_up_down:" : @"↕️", \
@":left_right_arrow:" : @"↔️", \
@":arrow_right_hook:" : @"↪️", \
@":leftwards_arrow_with_hook:" : @"↩️", \
@":arrow_heading_up:" : @"⤴️", \
@":arrow_heading_down:" : @"⤵️", \
@":twisted_rightwards_arrows:" : @"\\uD83D\\uDD00", \
@":repeat:" : @"\\uD83D\\uDD01", \
@":repeat_one:" : @"\\uD83D\\uDD02", \
@":arrows_counterclockwise:" : @"\\uD83D\\uDD04", \
@":arrows_clockwise:" : @"\\uD83D\\uDD03", \
@":musical_note:" : @"\\uD83C\\uDFB5", \
@":notes:" : @"\\uD83C\\uDFB6", \
@":heavy_plus_sign:" : @"➕", \
@":heavy_minus_sign:" : @"➖", \
@":heavy_division_sign:" : @"➗", \
@":heavy_multiplication_x:" : @"✖️", \
@":heavy_equals_sign:" : @"\\uD83D\\uDFF0", \
@":infinity:" : @"♾️", \
@":heavy_dollar_sign:" : @"\\uD83D\\uDCB2", \
@":currency_exchange:" : @"\\uD83D\\uDCB1", \
@":tm:" : @"™️", \
@":copyright:" : @"\\xa9️", \
@":registered:" : @"\\xae️", \
@":wavy_dash:" : @"〰️", \
@":curly_loop:" : @"➰", \
@":loop:" : @"➿", \
@":end:" : @"\\uD83D\\uDD1A", \
@":back:" : @"\\uD83D\\uDD19", \
@":on:" : @"\\uD83D\\uDD1B", \
@":top:" : @"\\uD83D\\uDD1D", \
@":soon:" : @"\\uD83D\\uDD1C", \
@":heavy_check_mark:" : @"✔️", \
@":ballot_box_with_check:" : @"☑️", \
@":radio_button:" : @"\\uD83D\\uDD18", \
@":white_circle:" : @"⚪", \
@":black_circle:" : @"⚫", \
@":red_circle:" : @"\\uD83D\\uDD34", \
@":blue_circle:" : @"\\uD83D\\uDD35", \
@":brown_circle:" : @"\\uD83D\\uDFE4", \
@":purple_circle:" : @"\\uD83D\\uDFE3", \
@":green_circle:" : @"\\uD83D\\uDFE2", \
@":yellow_circle:" : @"\\uD83D\\uDFE1", \
@":orange_circle:" : @"\\uD83D\\uDFE0", \
@":small_red_triangle:" : @"\\uD83D\\uDD3A", \
@":small_red_triangle_down:" : @"\\uD83D\\uDD3B", \
@":small_orange_diamond:" : @"\\uD83D\\uDD38", \
@":small_blue_diamond:" : @"\\uD83D\\uDD39", \
@":large_orange_diamond:" : @"\\uD83D\\uDD36", \
@":large_blue_diamond:" : @"\\uD83D\\uDD37", \
@":white_square_button:" : @"\\uD83D\\uDD33", \
@":black_square_button:" : @"\\uD83D\\uDD32", \
@":black_small_square:" : @"▪️", \
@":white_small_square:" : @"▫️", \
@":black_medium_small_square:" : @"◾", \
@":white_medium_small_square:" : @"◽", \
@":black_medium_square:" : @"◼️", \
@":white_medium_square:" : @"◻️", \
@":black_large_square:" : @"⬛", \
@":white_large_square:" : @"⬜", \
@":orange_square:" : @"\\uD83D\\uDFE7", \
@":blue_square:" : @"\\uD83D\\uDFE6", \
@":red_square:" : @"\\uD83D\\uDFE5", \
@":brown_square:" : @"\\uD83D\\uDFEB", \
@":purple_square:" : @"\\uD83D\\uDFEA", \
@":green_square:" : @"\\uD83D\\uDFE9", \
@":yellow_square:" : @"\\uD83D\\uDFE8", \
@":speaker:" : @"\\uD83D\\uDD08", \
@":mute:" : @"\\uD83D\\uDD07", \
@":sound:" : @"\\uD83D\\uDD09", \
@":loud_sound:" : @"\\uD83D\\uDD0A", \
@":bell:" : @"\\uD83D\\uDD14", \
@":no_bell:" : @"\\uD83D\\uDD15", \
@":mega:" : @"\\uD83D\\uDCE3", \
@":loudspeaker:" : @"\\uD83D\\uDCE2", \
@":speech_left:" : @"\\uD83D\\uDDE8️", \
@":left_speech_bubble:" : @"\\uD83D\\uDDE8️", \
@":eye_in_speech_bubble:" : @"\\uD83D\\uDC41‍\\uD83D\\uDDE8", \
@":speech_balloon:" : @"\\uD83D\\uDCAC", \
@":thought_balloon:" : @"\\uD83D\\uDCAD", \
@":anger_right:" : @"\\uD83D\\uDDEF️", \
@":right_anger_bubble:" : @"\\uD83D\\uDDEF️", \
@":spades:" : @"♠️", \
@":clubs:" : @"♣️", \
@":hearts:" : @"♥️", \
@":diamonds:" : @"♦️", \
@":black_joker:" : @"\\uD83C\\uDCCF", \
@":flower_playing_cards:" : @"\\uD83C\\uDFB4", \
@":mahjong:" : @"\\uD83C\\uDC04", \
@":clock1:" : @"\\uD83D\\uDD50", \
@":clock2:" : @"\\uD83D\\uDD51", \
@":clock3:" : @"\\uD83D\\uDD52", \
@":clock4:" : @"\\uD83D\\uDD53", \
@":clock5:" : @"\\uD83D\\uDD54", \
@":clock6:" : @"\\uD83D\\uDD55", \
@":clock7:" : @"\\uD83D\\uDD56", \
@":clock8:" : @"\\uD83D\\uDD57", \
@":clock9:" : @"\\uD83D\\uDD58", \
@":clock10:" : @"\\uD83D\\uDD59", \
@":clock11:" : @"\\uD83D\\uDD5A", \
@":clock12:" : @"\\uD83D\\uDD5B", \
@":clock130:" : @"\\uD83D\\uDD5C", \
@":clock230:" : @"\\uD83D\\uDD5D", \
@":clock330:" : @"\\uD83D\\uDD5E", \
@":clock430:" : @"\\uD83D\\uDD5F", \
@":clock530:" : @"\\uD83D\\uDD60", \
@":clock630:" : @"\\uD83D\\uDD61", \
@":clock730:" : @"\\uD83D\\uDD62", \
@":clock830:" : @"\\uD83D\\uDD63", \
@":clock930:" : @"\\uD83D\\uDD64", \
@":clock1030:" : @"\\uD83D\\uDD65", \
@":clock1130:" : @"\\uD83D\\uDD66", \
@":clock1230:" : @"\\uD83D\\uDD67", \
@":female_sign:" : @"♀️", \
@":male_sign:" : @"♂️", \
@":transgender_symbol:" : @"⚧", \
@":medical_symbol:" : @"⚕️", \
@":regional_indicator_z:" : @"\\uD83C\\uDDFF", \
@":regional_indicator_y:" : @"\\uD83C\\uDDFE", \
@":regional_indicator_x:" : @"\\uD83C\\uDDFD", \
@":regional_indicator_w:" : @"\\uD83C\\uDDFC", \
@":regional_indicator_v:" : @"\\uD83C\\uDDFB", \
@":regional_indicator_u:" : @"\\uD83C\\uDDFA", \
@":regional_indicator_t:" : @"\\uD83C\\uDDF9", \
@":regional_indicator_s:" : @"\\uD83C\\uDDF8", \
@":regional_indicator_r:" : @"\\uD83C\\uDDF7", \
@":regional_indicator_q:" : @"\\uD83C\\uDDF6", \
@":regional_indicator_p:" : @"\\uD83C\\uDDF5", \
@":regional_indicator_o:" : @"\\uD83C\\uDDF4", \
@":regional_indicator_n:" : @"\\uD83C\\uDDF3", \
@":regional_indicator_m:" : @"\\uD83C\\uDDF2", \
@":regional_indicator_l:" : @"\\uD83C\\uDDF1", \
@":regional_indicator_k:" : @"\\uD83C\\uDDF0", \
@":regional_indicator_j:" : @"\\uD83C\\uDDEF", \
@":regional_indicator_i:" : @"\\uD83C\\uDDEE", \
@":regional_indicator_h:" : @"\\uD83C\\uDDED", \
@":regional_indicator_g:" : @"\\uD83C\\uDDEC", \
@":regional_indicator_f:" : @"\\uD83C\\uDDEB", \
@":regional_indicator_e:" : @"\\uD83C\\uDDEA", \
@":regional_indicator_d:" : @"\\uD83C\\uDDE9", \
@":regional_indicator_c:" : @"\\uD83C\\uDDE8", \
@":regional_indicator_b:" : @"\\uD83C\\uDDE7", \
@":regional_indicator_a:" : @"\\uD83C\\uDDE6", \
@":flag_white:" : @"\\uD83C\\uDFF3️", \
@":flag_black:" : @"\\uD83C\\uDFF4", \
@":checkered_flag:" : @"\\uD83C\\uDFC1", \
@":triangular_flag_on_post:" : @"\\uD83D\\uDEA9", \
@":rainbow_flag:" : @"\\uD83C\\uDFF3️‍\\uD83C\\uDF08", \
@":gay_pride_flag:" : @"\\uD83C\\uDFF3️‍\\uD83C\\uDF08", \
@":transgender_flag:" : @"\\uD83C\\uDFF3️‍⚧️", \
@":pirate_flag:" : @"\\uD83C\\uDFF4‍☠️", \
@":flag_af:" : @"\\uD83C\\uDDE6\\uD83C\\uDDEB", \
@":flag_ax:" : @"\\uD83C\\uDDE6\\uD83C\\uDDFD", \
@":flag_al:" : @"\\uD83C\\uDDE6\\uD83C\\uDDF1", \
@":flag_dz:" : @"\\uD83C\\uDDE9\\uD83C\\uDDFF", \
@":flag_as:" : @"\\uD83C\\uDDE6\\uD83C\\uDDF8", \
@":flag_ad:" : @"\\uD83C\\uDDE6\\uD83C\\uDDE9", \
@":flag_ao:" : @"\\uD83C\\uDDE6\\uD83C\\uDDF4", \
@":flag_ai:" : @"\\uD83C\\uDDE6\\uD83C\\uDDEE", \
@":flag_aq:" : @"\\uD83C\\uDDE6\\uD83C\\uDDF6", \
@":flag_ag:" : @"\\uD83C\\uDDE6\\uD83C\\uDDEC", \
@":flag_ar:" : @"\\uD83C\\uDDE6\\uD83C\\uDDF7", \
@":flag_am:" : @"\\uD83C\\uDDE6\\uD83C\\uDDF2", \
@":flag_aw:" : @"\\uD83C\\uDDE6\\uD83C\\uDDFC", \
@":flag_au:" : @"\\uD83C\\uDDE6\\uD83C\\uDDFA", \
@":flag_at:" : @"\\uD83C\\uDDE6\\uD83C\\uDDF9", \
@":flag_az:" : @"\\uD83C\\uDDE6\\uD83C\\uDDFF", \
@":flag_bs:" : @"\\uD83C\\uDDE7\\uD83C\\uDDF8", \
@":flag_bh:" : @"\\uD83C\\uDDE7\\uD83C\\uDDED", \
@":flag_bd:" : @"\\uD83C\\uDDE7\\uD83C\\uDDE9", \
@":flag_bb:" : @"\\uD83C\\uDDE7\\uD83C\\uDDE7", \
@":flag_by:" : @"\\uD83C\\uDDE7\\uD83C\\uDDFE", \
@":flag_be:" : @"\\uD83C\\uDDE7\\uD83C\\uDDEA", \
@":flag_bz:" : @"\\uD83C\\uDDE7\\uD83C\\uDDFF", \
@":flag_bj:" : @"\\uD83C\\uDDE7\\uD83C\\uDDEF", \
@":flag_bm:" : @"\\uD83C\\uDDE7\\uD83C\\uDDF2", \
@":flag_bt:" : @"\\uD83C\\uDDE7\\uD83C\\uDDF9", \
@":flag_bo:" : @"\\uD83C\\uDDE7\\uD83C\\uDDF4", \
@":flag_ba:" : @"\\uD83C\\uDDE7\\uD83C\\uDDE6", \
@":flag_bw:" : @"\\uD83C\\uDDE7\\uD83C\\uDDFC", \
@":flag_br:" : @"\\uD83C\\uDDE7\\uD83C\\uDDF7", \
@":flag_io:" : @"\\uD83C\\uDDEE\\uD83C\\uDDF4", \
@":flag_vg:" : @"\\uD83C\\uDDFB\\uD83C\\uDDEC", \
@":flag_bn:" : @"\\uD83C\\uDDE7\\uD83C\\uDDF3", \
@":flag_bg:" : @"\\uD83C\\uDDE7\\uD83C\\uDDEC", \
@":flag_bf:" : @"\\uD83C\\uDDE7\\uD83C\\uDDEB", \
@":flag_bi:" : @"\\uD83C\\uDDE7\\uD83C\\uDDEE", \
@":flag_kh:" : @"\\uD83C\\uDDF0\\uD83C\\uDDED", \
@":flag_cm:" : @"\\uD83C\\uDDE8\\uD83C\\uDDF2", \
@":flag_ca:" : @"\\uD83C\\uDDE8\\uD83C\\uDDE6", \
@":flag_ic:" : @"\\uD83C\\uDDEE\\uD83C\\uDDE8", \
@":flag_cv:" : @"\\uD83C\\uDDE8\\uD83C\\uDDFB", \
@":flag_bq:" : @"\\uD83C\\uDDE7\\uD83C\\uDDF6", \
@":flag_ky:" : @"\\uD83C\\uDDF0\\uD83C\\uDDFE", \
@":flag_cf:" : @"\\uD83C\\uDDE8\\uD83C\\uDDEB", \
@":flag_td:" : @"\\uD83C\\uDDF9\\uD83C\\uDDE9", \
@":flag_cl:" : @"\\uD83C\\uDDE8\\uD83C\\uDDF1", \
@":flag_cn:" : @"\\uD83C\\uDDE8\\uD83C\\uDDF3", \
@":flag_cx:" : @"\\uD83C\\uDDE8\\uD83C\\uDDFD", \
@":flag_cc:" : @"\\uD83C\\uDDE8\\uD83C\\uDDE8", \
@":flag_co:" : @"\\uD83C\\uDDE8\\uD83C\\uDDF4", \
@":flag_km:" : @"\\uD83C\\uDDF0\\uD83C\\uDDF2", \
@":flag_cg:" : @"\\uD83C\\uDDE8\\uD83C\\uDDEC", \
@":flag_cd:" : @"\\uD83C\\uDDE8\\uD83C\\uDDE9", \
@":flag_ck:" : @"\\uD83C\\uDDE8\\uD83C\\uDDF0", \
@":flag_cr:" : @"\\uD83C\\uDDE8\\uD83C\\uDDF7", \
@":flag_ci:" : @"\\uD83C\\uDDE8\\uD83C\\uDDEE", \
@":flag_hr:" : @"\\uD83C\\uDDED\\uD83C\\uDDF7", \
@":flag_cu:" : @"\\uD83C\\uDDE8\\uD83C\\uDDFA", \
@":flag_cw:" : @"\\uD83C\\uDDE8\\uD83C\\uDDFC", \
@":flag_cy:" : @"\\uD83C\\uDDE8\\uD83C\\uDDFE", \
@":flag_cz:" : @"\\uD83C\\uDDE8\\uD83C\\uDDFF", \
@":flag_dk:" : @"\\uD83C\\uDDE9\\uD83C\\uDDF0", \
@":flag_dj:" : @"\\uD83C\\uDDE9\\uD83C\\uDDEF", \
@":flag_dm:" : @"\\uD83C\\uDDE9\\uD83C\\uDDF2", \
@":flag_do:" : @"\\uD83C\\uDDE9\\uD83C\\uDDF4", \
@":flag_ec:" : @"\\uD83C\\uDDEA\\uD83C\\uDDE8", \
@":flag_eg:" : @"\\uD83C\\uDDEA\\uD83C\\uDDEC", \
@":flag_sv:" : @"\\uD83C\\uDDF8\\uD83C\\uDDFB", \
@":flag_gq:" : @"\\uD83C\\uDDEC\\uD83C\\uDDF6", \
@":flag_er:" : @"\\uD83C\\uDDEA\\uD83C\\uDDF7", \
@":flag_ee:" : @"\\uD83C\\uDDEA\\uD83C\\uDDEA", \
@":flag_et:" : @"\\uD83C\\uDDEA\\uD83C\\uDDF9", \
@":flag_eu:" : @"\\uD83C\\uDDEA\\uD83C\\uDDFA", \
@":flag_fk:" : @"\\uD83C\\uDDEB\\uD83C\\uDDF0", \
@":flag_fo:" : @"\\uD83C\\uDDEB\\uD83C\\uDDF4", \
@":flag_fj:" : @"\\uD83C\\uDDEB\\uD83C\\uDDEF", \
@":flag_fi:" : @"\\uD83C\\uDDEB\\uD83C\\uDDEE", \
@":flag_fr:" : @"\\uD83C\\uDDEB\\uD83C\\uDDF7", \
@":flag_gf:" : @"\\uD83C\\uDDEC\\uD83C\\uDDEB", \
@":flag_pf:" : @"\\uD83C\\uDDF5\\uD83C\\uDDEB", \
@":flag_tf:" : @"\\uD83C\\uDDF9\\uD83C\\uDDEB", \
@":flag_ga:" : @"\\uD83C\\uDDEC\\uD83C\\uDDE6", \
@":flag_gm:" : @"\\uD83C\\uDDEC\\uD83C\\uDDF2", \
@":flag_ge:" : @"\\uD83C\\uDDEC\\uD83C\\uDDEA", \
@":flag_de:" : @"\\uD83C\\uDDE9\\uD83C\\uDDEA", \
@":flag_gh:" : @"\\uD83C\\uDDEC\\uD83C\\uDDED", \
@":flag_gi:" : @"\\uD83C\\uDDEC\\uD83C\\uDDEE", \
@":flag_gr:" : @"\\uD83C\\uDDEC\\uD83C\\uDDF7", \
@":flag_gl:" : @"\\uD83C\\uDDEC\\uD83C\\uDDF1", \
@":flag_gd:" : @"\\uD83C\\uDDEC\\uD83C\\uDDE9", \
@":flag_gp:" : @"\\uD83C\\uDDEC\\uD83C\\uDDF5", \
@":flag_gu:" : @"\\uD83C\\uDDEC\\uD83C\\uDDFA", \
@":flag_gt:" : @"\\uD83C\\uDDEC\\uD83C\\uDDF9", \
@":flag_gg:" : @"\\uD83C\\uDDEC\\uD83C\\uDDEC", \
@":flag_gn:" : @"\\uD83C\\uDDEC\\uD83C\\uDDF3", \
@":flag_gw:" : @"\\uD83C\\uDDEC\\uD83C\\uDDFC", \
@":flag_gy:" : @"\\uD83C\\uDDEC\\uD83C\\uDDFE", \
@":flag_ht:" : @"\\uD83C\\uDDED\\uD83C\\uDDF9", \
@":flag_hn:" : @"\\uD83C\\uDDED\\uD83C\\uDDF3", \
@":flag_hk:" : @"\\uD83C\\uDDED\\uD83C\\uDDF0", \
@":flag_hu:" : @"\\uD83C\\uDDED\\uD83C\\uDDFA", \
@":flag_is:" : @"\\uD83C\\uDDEE\\uD83C\\uDDF8", \
@":flag_in:" : @"\\uD83C\\uDDEE\\uD83C\\uDDF3", \
@":flag_id:" : @"\\uD83C\\uDDEE\\uD83C\\uDDE9", \
@":flag_ir:" : @"\\uD83C\\uDDEE\\uD83C\\uDDF7", \
@":flag_iq:" : @"\\uD83C\\uDDEE\\uD83C\\uDDF6", \
@":flag_ie:" : @"\\uD83C\\uDDEE\\uD83C\\uDDEA", \
@":flag_im:" : @"\\uD83C\\uDDEE\\uD83C\\uDDF2", \
@":flag_il:" : @"\\uD83C\\uDDEE\\uD83C\\uDDF1", \
@":flag_it:" : @"\\uD83C\\uDDEE\\uD83C\\uDDF9", \
@":flag_jm:" : @"\\uD83C\\uDDEF\\uD83C\\uDDF2", \
@":flag_jp:" : @"\\uD83C\\uDDEF\\uD83C\\uDDF5", \
@":crossed_flags:" : @"\\uD83C\\uDF8C", \
@":flag_je:" : @"\\uD83C\\uDDEF\\uD83C\\uDDEA", \
@":flag_jo:" : @"\\uD83C\\uDDEF\\uD83C\\uDDF4", \
@":flag_kz:" : @"\\uD83C\\uDDF0\\uD83C\\uDDFF", \
@":flag_ke:" : @"\\uD83C\\uDDF0\\uD83C\\uDDEA", \
@":flag_ki:" : @"\\uD83C\\uDDF0\\uD83C\\uDDEE", \
@":flag_xk:" : @"\\uD83C\\uDDFD\\uD83C\\uDDF0", \
@":flag_kw:" : @"\\uD83C\\uDDF0\\uD83C\\uDDFC", \
@":flag_kg:" : @"\\uD83C\\uDDF0\\uD83C\\uDDEC", \
@":flag_la:" : @"\\uD83C\\uDDF1\\uD83C\\uDDE6", \
@":flag_lv:" : @"\\uD83C\\uDDF1\\uD83C\\uDDFB", \
@":flag_lb:" : @"\\uD83C\\uDDF1\\uD83C\\uDDE7", \
@":flag_ls:" : @"\\uD83C\\uDDF1\\uD83C\\uDDF8", \
@":flag_lr:" : @"\\uD83C\\uDDF1\\uD83C\\uDDF7", \
@":flag_ly:" : @"\\uD83C\\uDDF1\\uD83C\\uDDFE", \
@":flag_li:" : @"\\uD83C\\uDDF1\\uD83C\\uDDEE", \
@":flag_lt:" : @"\\uD83C\\uDDF1\\uD83C\\uDDF9", \
@":flag_lu:" : @"\\uD83C\\uDDF1\\uD83C\\uDDFA", \
@":flag_mo:" : @"\\uD83C\\uDDF2\\uD83C\\uDDF4", \
@":flag_mk:" : @"\\uD83C\\uDDF2\\uD83C\\uDDF0", \
@":flag_mg:" : @"\\uD83C\\uDDF2\\uD83C\\uDDEC", \
@":flag_mw:" : @"\\uD83C\\uDDF2\\uD83C\\uDDFC", \
@":flag_my:" : @"\\uD83C\\uDDF2\\uD83C\\uDDFE", \
@":flag_mv:" : @"\\uD83C\\uDDF2\\uD83C\\uDDFB", \
@":flag_ml:" : @"\\uD83C\\uDDF2\\uD83C\\uDDF1", \
@":flag_mt:" : @"\\uD83C\\uDDF2\\uD83C\\uDDF9", \
@":flag_mh:" : @"\\uD83C\\uDDF2\\uD83C\\uDDED", \
@":flag_mq:" : @"\\uD83C\\uDDF2\\uD83C\\uDDF6", \
@":flag_mr:" : @"\\uD83C\\uDDF2\\uD83C\\uDDF7", \
@":flag_mu:" : @"\\uD83C\\uDDF2\\uD83C\\uDDFA", \
@":flag_yt:" : @"\\uD83C\\uDDFE\\uD83C\\uDDF9", \
@":flag_mx:" : @"\\uD83C\\uDDF2\\uD83C\\uDDFD", \
@":flag_fm:" : @"\\uD83C\\uDDEB\\uD83C\\uDDF2", \
@":flag_md:" : @"\\uD83C\\uDDF2\\uD83C\\uDDE9", \
@":flag_mc:" : @"\\uD83C\\uDDF2\\uD83C\\uDDE8", \
@":flag_mn:" : @"\\uD83C\\uDDF2\\uD83C\\uDDF3", \
@":flag_me:" : @"\\uD83C\\uDDF2\\uD83C\\uDDEA", \
@":flag_ms:" : @"\\uD83C\\uDDF2\\uD83C\\uDDF8", \
@":flag_ma:" : @"\\uD83C\\uDDF2\\uD83C\\uDDE6", \
@":flag_mz:" : @"\\uD83C\\uDDF2\\uD83C\\uDDFF", \
@":flag_mm:" : @"\\uD83C\\uDDF2\\uD83C\\uDDF2", \
@":flag_na:" : @"\\uD83C\\uDDF3\\uD83C\\uDDE6", \
@":flag_nr:" : @"\\uD83C\\uDDF3\\uD83C\\uDDF7", \
@":flag_np:" : @"\\uD83C\\uDDF3\\uD83C\\uDDF5", \
@":flag_nl:" : @"\\uD83C\\uDDF3\\uD83C\\uDDF1", \
@":flag_nc:" : @"\\uD83C\\uDDF3\\uD83C\\uDDE8", \
@":flag_nz:" : @"\\uD83C\\uDDF3\\uD83C\\uDDFF", \
@":flag_ni:" : @"\\uD83C\\uDDF3\\uD83C\\uDDEE", \
@":flag_ne:" : @"\\uD83C\\uDDF3\\uD83C\\uDDEA", \
@":flag_ng:" : @"\\uD83C\\uDDF3\\uD83C\\uDDEC", \
@":flag_nu:" : @"\\uD83C\\uDDF3\\uD83C\\uDDFA", \
@":flag_nf:" : @"\\uD83C\\uDDF3\\uD83C\\uDDEB", \
@":flag_kp:" : @"\\uD83C\\uDDF0\\uD83C\\uDDF5", \
@":flag_mp:" : @"\\uD83C\\uDDF2\\uD83C\\uDDF5", \
@":flag_no:" : @"\\uD83C\\uDDF3\\uD83C\\uDDF4", \
@":flag_om:" : @"\\uD83C\\uDDF4\\uD83C\\uDDF2", \
@":flag_pk:" : @"\\uD83C\\uDDF5\\uD83C\\uDDF0", \
@":flag_pw:" : @"\\uD83C\\uDDF5\\uD83C\\uDDFC", \
@":flag_ps:" : @"\\uD83C\\uDDF5\\uD83C\\uDDF8", \
@":flag_pa:" : @"\\uD83C\\uDDF5\\uD83C\\uDDE6", \
@":flag_pg:" : @"\\uD83C\\uDDF5\\uD83C\\uDDEC", \
@":flag_py:" : @"\\uD83C\\uDDF5\\uD83C\\uDDFE", \
@":flag_pe:" : @"\\uD83C\\uDDF5\\uD83C\\uDDEA", \
@":flag_ph:" : @"\\uD83C\\uDDF5\\uD83C\\uDDED", \
@":flag_pn:" : @"\\uD83C\\uDDF5\\uD83C\\uDDF3", \
@":flag_pl:" : @"\\uD83C\\uDDF5\\uD83C\\uDDF1", \
@":flag_pt:" : @"\\uD83C\\uDDF5\\uD83C\\uDDF9", \
@":flag_pr:" : @"\\uD83C\\uDDF5\\uD83C\\uDDF7", \
@":flag_qa:" : @"\\uD83C\\uDDF6\\uD83C\\uDDE6", \
@":flag_re:" : @"\\uD83C\\uDDF7\\uD83C\\uDDEA", \
@":flag_ro:" : @"\\uD83C\\uDDF7\\uD83C\\uDDF4", \
@":flag_ru:" : @"\\uD83C\\uDDF7\\uD83C\\uDDFA", \
@":flag_rw:" : @"\\uD83C\\uDDF7\\uD83C\\uDDFC", \
@":flag_ws:" : @"\\uD83C\\uDDFC\\uD83C\\uDDF8", \
@":flag_sm:" : @"\\uD83C\\uDDF8\\uD83C\\uDDF2", \
@":flag_st:" : @"\\uD83C\\uDDF8\\uD83C\\uDDF9", \
@":flag_sa:" : @"\\uD83C\\uDDF8\\uD83C\\uDDE6", \
@":flag_sn:" : @"\\uD83C\\uDDF8\\uD83C\\uDDF3", \
@":flag_rs:" : @"\\uD83C\\uDDF7\\uD83C\\uDDF8", \
@":flag_sc:" : @"\\uD83C\\uDDF8\\uD83C\\uDDE8", \
@":flag_sl:" : @"\\uD83C\\uDDF8\\uD83C\\uDDF1", \
@":flag_sg:" : @"\\uD83C\\uDDF8\\uD83C\\uDDEC", \
@":flag_sx:" : @"\\uD83C\\uDDF8\\uD83C\\uDDFD", \
@":flag_sk:" : @"\\uD83C\\uDDF8\\uD83C\\uDDF0", \
@":flag_si:" : @"\\uD83C\\uDDF8\\uD83C\\uDDEE", \
@":flag_gs:" : @"\\uD83C\\uDDEC\\uD83C\\uDDF8", \
@":flag_sb:" : @"\\uD83C\\uDDF8\\uD83C\\uDDE7", \
@":flag_so:" : @"\\uD83C\\uDDF8\\uD83C\\uDDF4", \
@":flag_za:" : @"\\uD83C\\uDDFF\\uD83C\\uDDE6", \
@":flag_kr:" : @"\\uD83C\\uDDF0\\uD83C\\uDDF7", \
@":flag_ss:" : @"\\uD83C\\uDDF8\\uD83C\\uDDF8", \
@":flag_es:" : @"\\uD83C\\uDDEA\\uD83C\\uDDF8", \
@":flag_lk:" : @"\\uD83C\\uDDF1\\uD83C\\uDDF0", \
@":flag_bl:" : @"\\uD83C\\uDDE7\\uD83C\\uDDF1", \
@":flag_sh:" : @"\\uD83C\\uDDF8\\uD83C\\uDDED", \
@":flag_kn:" : @"\\uD83C\\uDDF0\\uD83C\\uDDF3", \
@":flag_lc:" : @"\\uD83C\\uDDF1\\uD83C\\uDDE8", \
@":flag_pm:" : @"\\uD83C\\uDDF5\\uD83C\\uDDF2", \
@":flag_vc:" : @"\\uD83C\\uDDFB\\uD83C\\uDDE8", \
@":flag_sd:" : @"\\uD83C\\uDDF8\\uD83C\\uDDE9", \
@":flag_sr:" : @"\\uD83C\\uDDF8\\uD83C\\uDDF7", \
@":flag_sz:" : @"\\uD83C\\uDDF8\\uD83C\\uDDFF", \
@":flag_se:" : @"\\uD83C\\uDDF8\\uD83C\\uDDEA", \
@":flag_ch:" : @"\\uD83C\\uDDE8\\uD83C\\uDDED", \
@":flag_sy:" : @"\\uD83C\\uDDF8\\uD83C\\uDDFE", \
@":flag_tw:" : @"\\uD83C\\uDDF9\\uD83C\\uDDFC", \
@":flag_tj:" : @"\\uD83C\\uDDF9\\uD83C\\uDDEF", \
@":flag_tz:" : @"\\uD83C\\uDDF9\\uD83C\\uDDFF", \
@":flag_th:" : @"\\uD83C\\uDDF9\\uD83C\\uDDED", \
@":flag_tl:" : @"\\uD83C\\uDDF9\\uD83C\\uDDF1", \
@":flag_tg:" : @"\\uD83C\\uDDF9\\uD83C\\uDDEC", \
@":flag_tk:" : @"\\uD83C\\uDDF9\\uD83C\\uDDF0", \
@":flag_to:" : @"\\uD83C\\uDDF9\\uD83C\\uDDF4", \
@":flag_tt:" : @"\\uD83C\\uDDF9\\uD83C\\uDDF9", \
@":flag_tn:" : @"\\uD83C\\uDDF9\\uD83C\\uDDF3", \
@":flag_tr:" : @"\\uD83C\\uDDF9\\uD83C\\uDDF7", \
@":flag_tm:" : @"\\uD83C\\uDDF9\\uD83C\\uDDF2", \
@":flag_tc:" : @"\\uD83C\\uDDF9\\uD83C\\uDDE8", \
@":flag_vi:" : @"\\uD83C\\uDDFB\\uD83C\\uDDEE", \
@":flag_tv:" : @"\\uD83C\\uDDF9\\uD83C\\uDDFB", \
@":flag_ug:" : @"\\uD83C\\uDDFA\\uD83C\\uDDEC", \
@":flag_ua:" : @"\\uD83C\\uDDFA\\uD83C\\uDDE6", \
@":flag_ae:" : @"\\uD83C\\uDDE6\\uD83C\\uDDEA", \
@":flag_gb:" : @"\\uD83C\\uDDEC\\uD83C\\uDDE7", \
@":england:" : @"\\uD83C\\uDFF4\\uDB40\\uDC67\\uDB40\\uDC62\\uDB40\\uDC65\\uDB40\\uDC6E\\uDB40\\uDC67\\uDB40\\uDC7F", \
@":scotland:" : @"\\uD83C\\uDFF4\\uDB40\\uDC67\\uDB40\\uDC62\\uDB40\\uDC73\\uDB40\\uDC63\\uDB40\\uDC74\\uDB40\\uDC7F", \
@":wales:" : @"\\uD83C\\uDFF4\\uDB40\\uDC67\\uDB40\\uDC62\\uDB40\\uDC77\\uDB40\\uDC6C\\uDB40\\uDC73\\uDB40\\uDC7F", \
@":flag_us:" : @"\\uD83C\\uDDFA\\uD83C\\uDDF8", \
@":flag_uy:" : @"\\uD83C\\uDDFA\\uD83C\\uDDFE", \
@":flag_uz:" : @"\\uD83C\\uDDFA\\uD83C\\uDDFF", \
@":flag_vu:" : @"\\uD83C\\uDDFB\\uD83C\\uDDFA", \
@":flag_va:" : @"\\uD83C\\uDDFB\\uD83C\\uDDE6", \
@":flag_ve:" : @"\\uD83C\\uDDFB\\uD83C\\uDDEA", \
@":flag_vn:" : @"\\uD83C\\uDDFB\\uD83C\\uDDF3", \
@":flag_wf:" : @"\\uD83C\\uDDFC\\uD83C\\uDDEB", \
@":flag_eh:" : @"\\uD83C\\uDDEA\\uD83C\\uDDED", \
@":flag_ye:" : @"\\uD83C\\uDDFE\\uD83C\\uDDEA", \
@":flag_zm:" : @"\\uD83C\\uDDFF\\uD83C\\uDDF2", \
@":flag_zw:" : @"\\uD83C\\uDDFF\\uD83C\\uDDFC", \
@":flag_ac:" : @"\\uD83C\\uDDE6\\uD83C\\uDDE8", \
@":flag_bv:" : @"\\uD83C\\uDDE7\\uD83C\\uDDFB", \
@":flag_cp:" : @"\\uD83C\\uDDE8\\uD83C\\uDDF5", \
@":flag_ea:" : @"\\uD83C\\uDDEA\\uD83C\\uDDE6", \
@":flag_dg:" : @"\\uD83C\\uDDE9\\uD83C\\uDDEC", \
@":flag_hm:" : @"\\uD83C\\uDDED\\uD83C\\uDDF2", \
@":flag_mf:" : @"\\uD83C\\uDDF2\\uD83C\\uDDEB", \
@":flag_sj:" : @"\\uD83C\\uDDF8\\uD83C\\uDDEF", \
@":flag_ta:" : @"\\uD83C\\uDDF9\\uD83C\\uDDE6", \
@":flag_um:" : @"\\uD83C\\uDDFA\\uD83C\\uDDF2", \
@":united_nations:" : @"\\uD83C\\uDDFA\\uD83C\\uDDF3", \
}